### ISSUE TITLE
目前好像不支持多种样式的Cell么？

### ISSUE THREAD

**Issue by dxxia** [qiankanglai/LoopScrollRect#100]
比如做聊天系统，cell可能有不同的样式，比如普通发言、队伍邀请、系统提示等，它们都是不同的对象。可以在加载的时候选择不同的cell样式进行加载么，而不是设置一个固定的prefab？

**Comment by qiankanglai** [comment]
可以的，不过需要微调下 LoopScrollPrefabSource.cs 传入idx，然后返回不同的prefab即可。目前的demo代码只是最简单的示例，具体肯定需要根据项目试用微调。

**Comment by dxxia** [comment]
好的，谢谢
