### ISSUE TITLE
help me 

### ISSUE THREAD

**Issue by Thunderkilll** [qiankanglai/LoopScrollRect#101]
Hello there my friend can you tell me is it possible for me to use this for a chat mini app where I have 2 kind of prefabs (sender and receiver) with your method where . I need this to optimize the charge of the application on the device i'm going t use and minimize the rendering process

**Comment by CodingFishWu** [comment]
Yes. Here is an example.
You can place 2 kind of prefabs into one GameObject Cell. And then implemente `ScrollCellIndex` method to show sender or receiver prefab.

**Comment by qiankanglai** [comment]
Sorry for late reply. In currect version, you could just make two kinds of prefabs into one and adjust them by `ScrollCellIndex` callback.

Please refer to `ScrollIndexCallback2.cs` for quick example.
