### ISSUE TITLE
建议封装成一个Unity Package Manger可识别的自定义包

### ISSUE THREAD

**Issue by SPingels** [qiankanglai/LoopScrollRect#102]
![Snipaste_2021-07-14_09-53-13](https://user-images.githubusercontent.com/11756371/125548310-a733df2e-324e-49c7-b746-90682130ea26.png)

**Comment by CodingFishWu** [comment]
感觉没什么意义。目前这个结构就挺清晰的了，导入即可使用。如果想封装成Unity Package，完全可以自行操作。

**Comment by qiankanglai** [comment]
抱歉看到的有点晚~
我随手封装了一个版本放branch分支了 https://github.com/qiankanglai/LoopScrollRect/tree/package
不过从我个人在项目使用来说确实没有太大意义... 因为本身就几个脚本塞进去就能用了

branch分支我暂时先维护着，如果以后有更多类似需求可以考虑合回master成为默认形式~
