### ISSUE TITLE
这个是否没有考虑到cell节点的缩放？

### ISSUE THREAD

**Issue by lvyan335156738** [qiankanglai/LoopScrollRect#104]
我试了demo里如果修改Scale来缩放cell节点，滑动时列表会有瞬间上下跳动的问题。缩放content节点也是如此。

**Comment by qiankanglai** [comment]
抱歉前段时间项目太忙都没空看github...
你是运行起来之后动态修改scale么？我本地试了下没复现出来，方便贴个gif看下具体怎么触发么？
ps. 如果是全局缩放不建议改Content，直接修改Scroll节点缩放好一些

**Comment by lvyan335156738** [comment]
感谢您百忙之中的回复。
不是运行起来修改，非运行状态改的。
具体的效果如下
![test2](https://user-images.githubusercontent.com/31239367/140905835-9609dea3-141e-4b58-9329-b9b2338fa888.gif)
滑动过程中会有瞬间的跳动卡顿
缩放后的content节点信息如下
![Snipaste_2021-11-09_18-08-25](https://user-images.githubusercontent.com/31239367/140906055-256de113-792e-4a54-bfd8-7aade5f99101.png)


如果不缩放content，只缩放cell也会出现相同效果
缩放后的cell节点信息如下
![Snipaste_2021-11-09_18-18-50](https://user-images.githubusercontent.com/31239367/140906337-e3336e07-2728-4247-8c30-f584911096d7.png)
同时缩放cell后，因为需要让cell之间的间距在显示上依旧保持原本的距离，于是修改了content上Gird的Spacing为负值，不知是否与此有关
![Snipaste_2021-11-09_18-10-57](https://user-images.githubusercontent.com/31239367/140906675-cd23b9ec-d573-4d49-a92d-47630183db63.png)

缩放Scroll节点没有出现此问题，但因为我的Scroll节点的大小适配是以边界的固定距离适配的，所以缩放Scroll节点适配上会出现问题，故没有采用缩放scroll的方式，谢谢您的建议。

**Comment by qiankanglai** [comment]
实在抱歉最近一个月公司的事情忙到天昏地暗orz
这个问题确实存在，我在master上修复了一下这两个使用案例~

- 处理了Content的scale不为1的情况
- 处理了Grid的spacing可能为负的情况

感谢反馈的问题 😃

**Comment by lvyan335156738** [comment]
确实解决了，十分感谢！
