### ISSUE TITLE
跳转到最底部的回弹问题

### ISSUE THREAD

**Issue by JohnYoung404** [qiankanglai/LoopScrollRect#106]
我使用的是正常的垂直方向的控件(没有reverse)，想每次更新数据后跳转到最底部，做类似聊天室的功能。
但是我发现normalized position设置为1.0之后，会有回弹的现象；
同时我试了下Demo场景里的例子，RefillFromEnd的时候，会有回弹现象；Refill则没有这个问题；
我没有想到怎么解决回弹的问题。
不知道是不是从末端refill的时候没有考虑padding之类的，但是好像示例里没有设置padding...

**Comment by qiankanglai** [comment]
抱歉最近忙于项目 反馈的比较慢orz
我看了下这个问题存在的原因是spacing(调大之后还是挺明显的)，在master上修复了下~

**Comment by JohnYoung404** [comment]
好的，感谢
