### ISSUE TITLE
HorizontalScroll_RandomSize 用 Scrollbar 慢慢拖動會有回彈的問題

### ISSUE THREAD

**Issue by SyaoranChang** [qiankanglai/LoopScrollRect#107]
你好,

HorizontalScroll_RandomSize 用 水平 Scrollbar 慢慢拖動會有回彈的問題
看起來是 剛好在新增下一個 Item 的時候，就會往回跳一下
然後我測試把它改成 VerticalScroll_RandomSize 用 垂直 Scrollbar 慢慢拖動則是正常的

**Comment by qiankanglai** [comment]
这个问题确实存在：RandomSize的物体配合ScrollBar使用会出现 滑动条回弹以及滑动条大小变化的问题。

出现的原因是LoopScrollBar机制导致无法精确的获得所有Item的高度之和(因为屏幕外的元素压根没有加载)，目前我是通过现有元素的平均值去估算的... 

最粗暴的做法是暴露接口让外部逻辑来提供值，但是要求用户提供精确值就挺麻烦的orz 暂时我还没想到更好的思路

**Comment by qiankanglai** [comment]
我补了一个可选接口，如果能提供精确的大小估计，那么scrollbar可以保持稳定orz

**Comment by SyaoranChang** [comment]
感謝
更新後 測試 DemoScene 的 HorizontalScroll_RandomSize 目前看起來正常了

**Comment by SyaoranChang** [comment]
剛剛再修改發現如果把亂數寬度改成這樣
就又會有拖動時回彈的問題...
原本的
private static float[] randomWidths = new float[3] { 100, 150, 50 };
修改後
private static float[] randomWidths = new float[3] { 50, 100, 150 };

**Comment by SyaoranChang** [comment]
剛剛沒看清楚，以為 SizeHelper2 是通用的
沒注意到它有指定 ScrollIndexCallback2

**Comment by SyaoranChang** [comment]
你好,

我有改寫了你的做法
並新增了幾個檔案 讓 SizeHelper.cs 能做通用使用

我有新增了 pull requests 看你覺得這樣改如何?
Improve scrollbar base on LoopScrollSizeHelper, add UseMultiPrefabs sample #109

**Comment by qiankanglai** [comment]
感谢PR，已merge。

不过还有一个细节比较麻烦：当启用MultiPrefab优化的时候，`TempPool`机制就会出问题（因为TempPool里的元素不是完全相同的东西了） 这个我一会儿补交一下。

**Comment by qiankanglai** [comment]
顺便补充一句，`SizeHelper`这个接口属于可选项，当提供的时候就能够帮助精准定位scrollbar；但是很多时候其实普通用户不太方便计算这个，所以我没有抽象成必须提供的接口（不提供的时候就相当于fallback到估算的模式）
