### ISSUE TITLE
Trying to remove **** from rebuild list while we are already inside a rebuild loop. This is not supported.

### ISSUE THREAD

**Issue by Nidre** [qiankanglai/LoopScrollRect#11]
Probably related to #6 to be appearing on Unity 5.6 again. Even for normal ScrollRect seems.

I'm getting this error about 24 times when I start the game. If I remove references to Horizontal and Vertical Scrollbars. I only get 1 of them. But the scrolling doesn't work properly jumps around a lot and still seems to update scrollbars even tho they are not assigned in editor.Trying to remove LogRow(Clone) (UnityEngine.UI.Text) from rebuild list while we are already inside a rebuild loop. This is not supported.

![image](https://cloud.githubusercontent.com/assets/6220948/26275750/762c76f8-3d68-11e7-823b-dec40b2f7119.png)

Trying to remove LogRow (UnityEngine.UI.Text) from rebuild list while we are already inside a rebuild loop. This is not supported. UnityEngine.GameObject:SetActive(Boolean) Pool:AddObjectToPool(PoolObject) (at Assets/Plugins/Internal/ScrollRectLoop/EasyObjectPool/EasyObjectPool.cs:72) Pool:ReturnObjectToPool(PoolObject) (at Assets/Plugins/Internal/ScrollRectLoop/EasyObjectPool/EasyObjectPool.cs:153) ResourceManager:ReturnObjectToPool(GameObject) (at Assets/Plugins/Internal/ScrollRectLoop/EasyObjectPool/ResourceManager.cs:109) UnityEngine.UI.LoopScrollRect:LateUpdate()

**Comment by Nidre** [comment]
Completely deleting Scrollbars from hierarchy seems to be prevent the issue from happening.

**Comment by Nidre** [comment]
Update seems like scrollbar issue was due to my own code. But a single error about this issue still appears at the beginning.

`Trying to remove LogRow(Clone) (UnityEngine.UI.Text) from rebuild list while we are already inside a rebuild loop. This is not supported.
UnityEngine.GameObject:SetActive(Boolean)
Pool:AddObjectToPool(PoolObject) (at Assets/Plugins/Internal/ScrollRectLoop/EasyObjectPool/EasyObjectPool.cs:72)
Pool:.ctor(String, GameObject, GameObject, Int32, PoolInflationType) (at Assets/Plugins/Internal/ScrollRectLoop/EasyObjectPool/EasyObjectPool.cs:62)
ResourceManager:InitPool(String, Int32, PoolInflationType) (at Assets/Plugins/Internal/ScrollRectLoop/EasyObjectPool/ResourceManager.cs:51)
ResourceManager:GetObjectFromPool(String, Boolean, Int32) (at Assets/Plugins/Internal/ScrollRectLoop/EasyObjectPool/ResourceManager.cs:67)
UnityEngine.UI.LoopScrollRect:LateUpdate()
`

**Comment by qiankanglai** [comment]
Would you mind post a simple project so I can check this issue. and 5.6.0?

**Comment by Nidre** [comment]
I will try to get something together for you. Yes 5.6.0

https://unity3d.com/unity/whats-new/unity-5.6.0

**Comment by qiankanglai** [comment]
Hi Nidre,
any update? I test my demo with 5.6.1 and it seems fine

**Comment by veboys** [comment]
i have the same issue when the scrollrect has a scrollbar

**Comment by abhishek02894** [comment]
i have the same issue.
error : -  Trying to remove CancelButton-Text (TMPro.TextMeshProUGUI) from rebuild list while we are already inside a rebuild loop. This is not supported.

**Comment by qiankanglai** [comment]
> i have the same issue. error : - Trying to remove CancelButton-Text (TMPro.TextMeshProUGUI) from rebuild list while we are already inside a rebuild loop. This is not supported.

Could you provide a small example for reproducing the problem?
