### ISSUE TITLE
請求幫助，請問如果我要在按鈕加上Callback事件，建議放在哪邊呢?

### ISSUE THREAD

**Issue by SyaoranChang** [qiankanglai/LoopScrollRect#111]
你好,

請問如果我要在 ScrollIndexCallback 按鈕加上Callback事件，建議放在哪邊呢?
我想了一下只想到放在 LoopScrollPrefabSource 的 GameObject GetObject(int index) 產生物件後
onClick.RemoveListener()移除事件
onClick.AddListener()再加上事件
這樣來避免從Pool中拿回來的重新加入事件

而不放在 ScrollIndexCallback 的 ScrollCellIndex() 裡面
是因為 如果有使用了 MultiPrefab 時，可能有多種 ScrollIndexCallback
這樣會需要每個裡面都要寫事件，會不太好維護

不知道有沒有其他更好的想法?

**Comment by qiankanglai** [comment]
其实从我个人之前的设计及项目使用来说，最早确实只考虑了单prefab source的情况，所以直接往`ScrollCellIndex`里写就行（填充数据、刷新绑定等操作）都在里面完成。

对于多multi prefab目前我也只能想到在GetObject的地方；还有一个可能的策略就是prefab上剥离一个基类，然后在`ScrollCellIndex`调用基类的`RefreshListener`。

**Comment by SyaoranChang** [comment]
有點不太懂你說的 呼叫 RefreshListener 的流程

**Comment by SyaoranChang** [comment]
1.我是想到把 Callback function 寫成 public Static 讓不同的 prefab 來共用
這樣就不用每次都要建立自定義的 InitOnStart_Custom 繼承自 InitOnStartMultiBase 並修改各自修改

2.關於初始化 InitOnStartMultiBase.cs 的兩個參數 
LoopScrollRectMulti m_LoopScrollRect;
 LoopListBankBase m_LoopListBank;
改用直接拖曳到 prefab 上面的方式初始化
避免遇到 Awake() 因為檔案名稱等原因，造成不是預期的初始化順序
導致要使用時，可能先執行了UI_ControllData 的 Awake()
之後才執行 InitOnStartMultiBase 的  Awake()
所以沒能先執行 GetComponent() 來取得資源
造成null 的紅字問題

我修改好 也提交 pull request 了
 Use Static common callback function for multiprefab and more #113

**Comment by qiankanglai** [comment]
收到，非常感谢~ 我得周末来跟进了，最近工作日负荷有点大orz

**Comment by qiankanglai** [comment]
我在PR之后补了两个小的更新，一个是删掉InitOnStart_Custom，直接使用InitOnStartMultiBase就行了；另一个是个人习惯绑定回调的时候用`RemoveAllListeners`确保清理干净（之前吃过亏 🤣 )

我觉得目前这个方法对于Multi Prefab还是相对比较清晰的

**Comment by SyaoranChang** [comment]
感謝
我這邊實際用會新增一個類別並繼承 InitOnStartMulti 或 ScrollIndexCallbackBase 來新增功能
避免修改 這個插件的檔案方便更新這邊的版本

關於 ScrollIndexCallback_Custom.cs
會用 RemoveListener 也是擔心怕有其他人也有新增事件，用 RemoveAllListeners 把其他人加的也全部清除
不過在這個範例因為 ScrollCellIndex 進來時 算是新物件，確實用這個是比較保險沒錯
