### ISSUE TITLE
請求幫助，需要紀錄玩家上次點擊的Index，下次玩家滑動到指定的Index，要更新指定的Cell

### ISSUE THREAD

**Issue by SyaoranChang** [qiankanglai/LoopScrollRect#114]
你好,

我現在實際使用時
A圖示為比較灰暗的圖
B圖示為比較明亮的圖

原本 Cell 的按鈕的圖示預設為A圖示
當玩家點擊了某個 Cell 的按鈕時，需要將它切換成B圖示
而其他所有Cell 按鈕都切換回A圖示
所以會需要紀錄玩家上次點擊的Index，下次玩家滑動到指定的Index，要更新相關影響的 Cell 的按鈕圖示
在想是不是能在 LoopScrollRectBase 內紀錄按下的 Index
ProvideData 時，也能順便傳進去方便後續的更新處理
只是在 重新排序等狀況時可能要重置Index為0

或是能再紀錄玩家點擊的資料用 object 存起來
ProvideData 一起回傳之類的

**Comment by qiankanglai** [comment]
`ProvideData`调用时候其实已经有index了，这时候可以存下来，例如https://github.com/qiankanglai/LoopScrollRect/blob/master/Assets/Demo/Scripts/ScrollIndexCallback_Custom.cs#L11 这里直接保存一个mIndex。

然后在OnButtonScrollIndexCallbackClick里把点击信息存到外部的数据源（当然这里其实用lambda表达式来达到这个目的了）

**Comment by qiankanglai** [comment]
是的 😄 
这个尽量避免放在LoopScrollRect本身里，在绑定使用的地方相对清晰

**Comment by SyaoranChang** [comment]
結果今天測試了我上面說的結果是不行的
因為這樣會導致 UI_ControllData_Horizontal 跟 UI_ControllData_Vertical
裡面的 ScrollIndexCallbackBase  都共用這個變數..
點了其中一邊的、另一邊的也會跟著連動...

**Comment by qiankanglai** [comment]
> 另外想到 在 ScrollIndexCallbackBase 新增 Static 變數來存Click 的 Index

> 因為這樣會導致 UI_ControllData_Horizontal 跟 UI_ControllData_Vertical

这里怪我没表达清楚orz 我本来想表达的意思是可以放一个通用的static回调，但是存的地方不能是static的，不然确实会互相污染。

感谢PR，已merge
