### ISSUE TITLE
HorizontalScroll_RandomSize 或 VerticalScroll_CustomSize 數量加到80個左右時，拖動後的Smooth動畫會卡卡的

### ISSUE THREAD

**Issue by SyaoranChang** [qiankanglai/LoopScrollRect#116]
你好,

實作時遇到數量夠多如80個以上時
往下或往上拖動後，Smooth動畫 在快停止的時候會有點跳動卡卡的感覺
可能DemoScene_MultiCell 範例沒有限FPS張數(約 460上下)所以沒那麼明顯
但是如果顯示到FPS60張時就會感覺出來，Smooth動畫快停止時不太順暢
不知道這是Unity 本身Scroll相關元件的問題嗎?

**Comment by qiankanglai** [comment]
我本地尝试了下 total count增加到80，然后滑动的效果看上去正常。
方便看下Hierarchy里是否的物体个数是否正常么？理论上LoopScroll始终只有屏幕中的几个元素，和总的个数没有直接联系

**Comment by SyaoranChang** [comment]
我有新增了 pull request
 Add UI control scene to set fps and more #118 

主要是新增了 UI_ControlScene 用來設定了 FPS
只要FPS為60，再來拖動後，再快停止的時候，就會感覺 Smooth動畫會卡卡的

**Comment by qiankanglai** [comment]
我研究了一下，出现卡卡的感觉其实是因为最后没“停止干净”，有轻微的偏移导致的。

我自己修了一下，然后去翻了翻UGUI代码的时候发现它其实也做了类似处理 https://github.com/Unity-Technologies/uGUI/blame/2019.1/UnityEngine.UI/UI/Core/ScrollRect.cs#L818 (对应Unity 5.4的实现，我当时应该是在5.1基础上做的所以一直没有带上orz)

**Comment by SyaoranChang** [comment]
剛剛測試了一下
看起來應該沒有太大的問題了
感謝了
