### ISSUE TITLE
What is the replacement to objectsToFill in latest updates?

### ISSUE THREAD

**Issue by roointan** [qiankanglai/LoopScrollRect#117]
I was using an older version, and was using objectsToFill as the actual holder for data, passing a single data item each item.
After update I see it's not in the code anymore.
What's the recommended method for holding data now?
I mean, LoopScrollArraySource is also removed.

**Comment by qiankanglai** [comment]
Sorry for the breaking change.  Implementing `LoopScrollDataSource` is the way suggested now (refer to https://github.com/qiankanglai/LoopScrollRect/blob/master/Assets/Demo/Scripts/InitOnStart.cs#L36). For convenience, you can just hold data outside and feed them using this interface.

The previous way (holding two types of data source inside) is a bit awkward.

**Comment by roointan** [comment]
@qiankanglai Thanks so much! 
I ended up copying the old code of LoopScrollArraySource (implementing LoopScrollDataSource), and keep it in a separate class. It's now used to wrap data, and ProvideData to LoopScrollRect.
And thank you so much for keeping this up to date. The old version was slow on refresh (we were doing screen fading on screen switch and it was slow..). I was going to fix Parent Transform changing, but noticed there is a new version with improvements, and It's all working great!
Happy I didn't have to fix that myself ;)
