### ISSUE TITLE
Cell中点击事件错乱

### ISSUE THREAD

**Issue by EricInCD** [qiankanglai/LoopScrollRect#12]
你好，在使用中出现了以下问题：
在Cell中加入一个Button，滚动列表，然后点击任一Cell中的button，会发现点击事件会被调用多次，而且顺序错乱。
Cell 11is Clicked
Cell 24is Clicked
Cell 37is Clicked
Cell 25is Clicked
Cell 11is Clicked
...
请教这个如何解决，谢谢！

**Comment by qiankanglai** [comment]
能否提供一个最小可运行的工程

**Comment by EricInCD** [comment]
我就用你的Demo试的，在名叫ScrollCell1的Prefab中添加一个按钮，将ScrollIndexCallback1的ScrollCellIndex方法做如下修改：
    void ScrollCellIndex(int idx)
    {
        string name = "Cell " + idx.ToString();
        if (text != null)
        {
            text.text = name;
        }
        if (image != null)
        {
            image.color = Rainbow(idx / 50.0f);
        }
        gameObject.name = name;
        gameObject.GetComponent<Button>().onClick.AddListener(() =>
        {
            Debug.Log(name + "is Clicked");
        });
    }
然后随意滚动列表，再点击任意一个Cell中的按钮。就能重现。

**Comment by EricInCD** [comment]
直接监听Cell上的Button组件的点击事件，也会得到类似的结果。

**Comment by qiankanglai** [comment]
```
button.onClick.AddListener(() =>
{
Debug.Log(name + "is Clicked");
});
```
在执行这个之前你先RemoveAllListeners()一下

**Comment by EricInCD** [comment]
好的，非常感谢！！！

**Comment by qiankanglai** [comment]
因为cell是不断复用的，所以ScrollIndex传进来的时候不一定和之前一致，如果不RemoveAll就会绑定多个产生混乱了～
