### ISSUE TITLE
当只放一个子物品，且Content的高度比Scroll小的情况下，会不停抖动

### ISSUE THREAD

**Issue by qpyghb** [qiankanglai/LoopScrollRect#121]
https://user-images.githubusercontent.com/26578944/151348414-f55b95e6-0c77-49d2-af10-a875a90ff994.mov

**Comment by qiankanglai** [comment]
感谢反馈，计算Bound的时候这个问题确实存在(我漏了一处`AdjustBound`的调用)。最新的提交已修复，我本地测试这个情况没问题了~

**Comment by SyaoranChang** [comment]
你好
我剛剛更新了你新的fix
在往左拖動後，有時會有閃一下的問題
重現的方式，可以刪除到剩下2個左右物件時
再來往左右拖動就會有高機率重現
影片:
https://user-images.githubusercontent.com/18550228/152754461-703cf182-1be6-4745-b1a8-d81acb530915.mp4

**Comment by qiankanglai** [comment]
> 你好 我剛剛更新了你新的fix 在往左拖動後，有時會有閃一下的問題 重現的方式，可以刪除到剩下2個左右物件時 再來往左右拖動就會有高機率重現 影片: https://user-images.githubusercontent.com/18550228/152754461-703cf182-1be6-4745-b1a8-d81acb530915.mp4

非常感谢~这个使用场景需要细节测试比较多，最新的提交修复了这个问题(`SetNormalizedPosition`里没考虑未填满的情况orz)

**Comment by qpyghb** [comment]
更新后正常了
