### ISSUE TITLE
新版本似乎會自動開關 Scrollbar 的元件

### ISSUE THREAD

**Issue by SyaoranChang** [qiankanglai/LoopScrollRect#123]
你好
不知道是不是從 sync again with ScrollRect @ 2019.1 的更新後
現在新版本似乎會自動開關 Scrollbar 的元件
剛剛合併到我實際用的專案才發現這個問題
之前我都只是把 Scrollbar 隱藏起來保留功能避免之後會用到
不知道有沒有辦法加個 是否自動開啟隱藏跟顯示 Scrollbar 的旗標來設定是否啟用這個功能?
我現在是從 LoopVerticalScrollRectMulti 設定面板中 移除 Scrollbar 的連結，避免自動開關的功能讓 Scrollbar 顯示出來的方式處理

**Comment by qiankanglai** [comment]
这块代码确实在同步的时候有修改到 https://github.com/qiankanglai/LoopScrollRect/commit/6dada12b9794d4278cb1556ffb23dd4a42206a15#diff-53b9678f66d79a1b4c3995b31c337938032d0404c9166b8b0e998e02aec06354L1358 。原来的逻辑确实有点小问题，在Perament下始终不会修改显隐【公版是在5.5f的时候修改的行为 https://github.com/Unity-Technologies/uGUI/commit/7756611eb614929f9f6a6212c0312df1c7f1223e】。

我想了下还是尽量保持和公版一致：可以检查下Horzontal/Vertical Scrollbar Visibility是否满足你的需求？如果是Permanent就根据当前LoopScroll的方向决定；如果是AutoHide就根据内容来决定。

**Comment by SyaoranChang** [comment]
Horzontal/Vertical Scrollbar Visibility 我不管調整成哪個
Scrollbar 我隱藏起來後
在開啟介面後還是會自動顯示出來
算是我需要的是不自動顯示或隱藏的選項，是由使用者自行顯示或隱藏

**Comment by qiankanglai** [comment]
这块的逻辑确实是_scroll强制设置scrollbar_。
如果说需要手动控制的话，最简单的方法是在LoopScrollRect的`Horizontal/Vertical Scrollbar`里置空，然后代码可以完全控制去隐藏scrollbar；如果需要交给scroll控制就设置回`Horizontal/Vertical Scrollbar`。

我今天有在考虑`ScrollbarVisibility`这个枚举加一个类似`Custom`的值，但是一方面和原版Scroll区别不容易理解，另一方面从功能上来说其实就是前面说的手动档...

**Comment by SyaoranChang** [comment]
恩 目前就先手動移除資源參考連結的方式處理吧
