### ISSUE TITLE
建议把源码和demo分开2个工程

### ISSUE THREAD

**Issue by Eternity714** [qiankanglai/LoopScrollRect#125]
建议把源码和demo分开2个工程，现在这样的方式无法用submodule直接引用

**Comment by qiankanglai** [comment]
我之前根据建议做过一个unity package管理的版本，容我这周末再想想怎么弄比较方便

**Comment by Bian-Sh** [comment]
做unity package管理的版本

**Comment by koalli** [comment]
upm包一个比较好的方式是，demo在一个分支里，package目录在主分支里。
demo工程在Packages目录下以submodule的方式引入主分支。
发布的时候用主分支发布，修改demo的时候提交到demo分支。
demo分支目录结构像下面这样：
.
├─Assets
├─Library
├─Logs
├─Packages
│　└─dev (子模块，引入仓库的主分支)*
│　　 ├─Documentation
│　　 ├─Scripts
│　　 │   └─Editor
│　　 └─package.json (包描述文件)
└─ProjectSettings

**Comment by Eternity714** [comment]
> 我之前根据建议做过一个unity package管理的版本，容我这周末再想想怎么弄比较方便

我用github actions做了个自动更新package分支的功能，应该可以解决问题了

**Comment by qiankanglai** [comment]
感谢，看上去UPM是一个可行的方案，我这周末抽空跟进

**Comment by Bian-Sh** [comment]
美滋滋

**Comment by qiankanglai** [comment]
（非常抱歉过去一个月忙公司项目冲刺天昏地暗的orz 鸽到现在）
我看了下Unity的Package部分文档和[unity usd](https://github.com/Unity-Technologies/usd-unity-sdk/tree/dev/package/com.unity.formats.usd)做法，其实都不用分两个分支~

不过我最后直接偷懒了，主分支走Package内容，然后我本地单独拉一个开发工程指向它就行了，又不是不能用（划掉
