### ISSUE TITLE
在做聊天模块时，添加新消息，不刷新Item数量

### ISSUE THREAD

**Issue by wangeryin** [qiankanglai/LoopScrollRect#128]
1、样例DemoScene_MultiCell中, 当数据初始化只有{1, 2}时， 此时我添加(Add Data)第三个数据时 列表不刷新 要手动拖拽一下才会刷新.(后面把Refresh接口改成Refill解决了)
2、快速拖动的时候 GetObject(index) index数值会出现负值或者超出数据大小的值

**Comment by qiankanglai** [comment]
第一个问题我来跟进下
第二个看看能否剥离一个例子或者录个gif，我用sample和项目里暂时没找到触发方式

**Comment by qiankanglai** [comment]
非常抱歉终于腾出手来看了~ 第一个问题雀实，我修复了下Sample里的用法并优化了下`RefreshCells`
这个接口最初设计是用来原地刷新数据的，没有考虑到会增加的情况。当然用`RefillCells`也行，现在可以保证刷新位置一模一样

**Comment by wangeryin** [comment]
第二个问题后面查出来是我自己的问题。另外 建议在Awake阶段 对m_Content做判空处理，因为#热更的关系，插件代码我们都是动态AddComponent的, 导致Awake的时候m_Content为空。 虽然我们也可以改插件代码， 但习惯上是不动官方插件代码的，谢谢。

**Comment by qiankanglai** [comment]
明白，这个我晚上补一下，感谢 😃
