### ISSUE TITLE
实例化滚动组件时出现报错Assertion failed

### ISSUE THREAD

**Issue by Rolsieya** [qiankanglai/LoopScrollRect#129]
我在一个cell内添加了一个LoopVerticalScrollRect组件，在实例化时会报Assertion failed
![image](https://user-images.githubusercontent.com/30484799/160038097-c24ac5c2-7ed7-4909-8fc3-a464275fca47.png)

**Comment by Rolsieya** [comment]
找到问题了，在awake的时候有对锚点和中心点做检查，如果不是用工具生成的话会提示报错，但是这个报错很难定位
![image](https://user-images.githubusercontent.com/30484799/160043514-b86fb2ab-da6e-40a9-86e3-4199547ee8e5.png)

**Comment by qiankanglai** [comment]
orz 这块确实有一些潜规则搞得蛋疼，如果有别的提示方式建议欢迎pr~ 我暂时还没想到完全规避的方法

**Comment by conyard** [comment]
> 找到问题了，在awake的时候有对锚点和中心点做检查，如果不是用工具生成的话会提示报错，但是这个报错很难定位 ![image](https://user-images.githubusercontent.com/30484799/160043514-b86fb2ab-da6e-40a9-86e3-4199547ee8e5.png)

怎么规避这个问题？目前我就有个需求，列表里面套列表~~~~

不会是选择一个用非循环列表(非插件列表吧)？？

**Comment by conyard** [comment]
> orz 这块确实有一些潜规则搞得蛋疼，如果有别的提示方式建议欢迎pr~ 我暂时还没想到完全规避的方法

这个输出不够准确，让使用者，没法准确定位，也不知道怎么来修改Prefab的东西
是否可以改为 
`
Debug.Assert(GetAbsDimension(m_Content.pivot) == value, $"Awake False,GetAbsDimension(m_Content.pivot) == value, {GetAbsDimension(m_Content.pivot)} == {value}");
Debug.Assert(GetAbsDimension(m_Content.anchorMin) == value, $"Awake False,GetAbsDimension(m_Content.anchorMin) == value, {GetAbsDimension(m_Content.anchorMin)} == {value}");
Debug.Assert(GetAbsDimension(m_Content.anchorMax) == value, $"Awake False,GetAbsDimension(m_Content.anchorMax) == value, {GetAbsDimension(m_Content.anchorMax)} == {value}");
`

**Comment by qiankanglai** [comment]
> 
> 这个输出不够准确，让使用者，没法准确定位，也不知道怎么来修改Prefab的东西 是否可以改为
> 
> Debug.Assert(GetAbsDimension(m_Content.pivot) == value, $"Awake False,GetAbsDimension(m_Content.pivot) == value, {GetAbsDimension(m_Content.pivot)} == {value} , {this}");
> 
> Debug.Assert(GetAbsDimension(m_Content.anchorMin) == value, $"Awake False,GetAbsDimension(m_Content.anchorMin) == value, {GetAbsDimension(m_Content.anchorMin)} == {value} , {this}");
> 
> Debug.Assert(GetAbsDimension(m_Content.anchorMax) == value, $"Awake False,GetAbsDimension(m_Content.anchorMax) == value, {GetAbsDimension(m_Content.anchorMax)} == {value} , {this}");

感谢意见，确实这样清晰不少。方便的话可否来个pull request？最近项目上线窗口，暂时没法抽出手来维护orz

**Comment by conyard** [comment]
> > 这个输出不够准确，让使用者，没法准确定位，也不知道怎么来修改Prefab的东西 是否可以改为
> > Debug.Assert(GetAbsDimension(m_Content.pivot) == value, $"Awake False,GetAbsDimension(m_Content.pivot) == value, {GetAbsDimension(m_Content.pivot)} == {value} , {this}");
> > Debug.Assert(GetAbsDimension(m_Content.anchorMin) == value, $"Awake False,GetAbsDimension(m_Content.anchorMin) == value, {GetAbsDimension(m_Content.anchorMin)} == {value} , {this}");
> > Debug.Assert(GetAbsDimension(m_Content.anchorMax) == value, $"Awake False,GetAbsDimension(m_Content.anchorMax) == value, {GetAbsDimension(m_Content.anchorMax)} == {value} , {this}");
> 
> 感谢意见，确实这样清晰不少。方便的话可否来个pull request？最近项目上线窗口，暂时没法抽出手来维护orz

无权限~~~
![image](https://github.com/user-attachments/assets/d6864c98-a835-413b-bfc9-cff1555c9889)

**Comment by qiankanglai** [comment]
可以fork之后提交到fork出来的仓库，然后create pull request即可，感谢

**Comment by conyard** [comment]
> 可以fork之后提交到fork出来的仓库，然后create pull request即可，感谢

已经提交并创建 request了
