### ISSUE TITLE
希望 Unity Package 也能在 OpenUPM 上註冊

### ISSUE THREAD

**Issue by SyaoranChang** [qiankanglai/LoopScrollRect#131]
你好,

希望安裝插件的方法
可以額外新增使用 OpenUPM 的方式安裝
目前使用 Unity 內建的 git URL 來安裝的方式
會有開啟專案所有人都需要安裝 git 才能下載插件的問題
但使用 OpenUPM 就只要安裝插件的人 去下載安裝 openupm-cli 就可以了
之後就可以使用 Unity Package 來維護更新版本了

Open Source Unity Package Registry
https://github.com/openupm/openupm

**Comment by qiankanglai** [comment]
收到，我顺便也整理下tag/release等

**Comment by qiankanglai** [comment]
https://openupm.com/packages/me.qiankanglai.loopscrollrect/ 已同步上
