### ISSUE TITLE
当cell中需要使用toggle，与Content上挂载的ToggleGroup的AllowSwitchOff关联时

### ISSUE THREAD

**Issue by miuleung** [qiankanglai/LoopScrollRect#133]
如题所述：
因为cell为复用，滚动时cell中的toggle组件会被ToggleGroup的AllowSwitchOff自动设置，会出现toggle选中状态错乱的问题。
此时怎么正确展示Cell中的Toggle状态呢？
在看了很多ScrollRect复用的样例，好像都没有对这个问题有特殊说明或处理

**Comment by qiankanglai** [comment]
我本地测试了下，确实直接复用的时候会出现问题~

我觉得可以在上层脚本的处理下，记录下`ReturnObject`时当前被选中的物体出框的情况，然后在`ProvideData`里手动设置一次。

**Comment by miuleung** [comment]
确实可以这样做，只是我期望会有更好的思路。十分感谢
