### ISSUE TITLE
infinity loop scroll for Scroll Rect(MultiPrefab)

### ISSUE THREAD

**Issue by LexaMV** [qiankanglai/LoopScrollRect#135]
Could you please explain if it is possible to put infinity loop for multi prefabs? In the normal version, it is enough to set totalCount = -1, but this does not work for multi mode. A workaround is to increase the original m_ContentsForInitData array in the CustomListBank script to 1,000,000 values. But is it right?

**Comment by qiankanglai** [comment]
Set `totalCount=-1` should also work for multi mode. I just modify existing example with infinity mode like below
![1654415712437](https://user-images.githubusercontent.com/1546130/172041161-cbce5779-dc52-49f7-8520-a04e4498afd8.png)

There is only one detail to mention: https://github.com/qiankanglai/LoopScrollRect/commit/e1b39713e56eb8307c0bbeead8cde535bf3fdcbd#diff-b2700fc46a5a0dc0655ace183243247723bb91a5cbd48621b36ce085450accd0
