### ISSUE TITLE
LoopScroll does flicker in VR

### ISSUE THREAD

**Issue by vmp1r3** [qiankanglai/LoopScrollRect#136]
When I do user `LoopVerticalScrollRect`, it does flicker:
https://user-images.githubusercontent.com/14846427/171871086-f3d05b48-ddc4-4d63-b25a-f9a859abd3d9.mp4

LoopVerticalSrollRect:
<img width="382" alt="image" src="https://user-images.githubusercontent.com/14846427/171871347-68af7c39-11a6-4bb0-87e7-cee9d06e3173.png">

Content Object:
<img width="388" alt="image" src="https://user-images.githubusercontent.com/14846427/171871253-d4c2a7c1-f3f1-432b-853b-f6de56d8a8b5.png">

I have no idea why it does that, but it works pretty well not in VR.

**Comment by qiankanglai** [comment]
What's the `RenderMode` for `Canvas`? Does `pixel perfect` help?

I haven't tested in VR but will try to reproduce the problem.

**Comment by vmp1r3** [comment]
Ok, I have tested and it seems to be our project. I don't really understand why does plugin fail on this assertations... Any guess?
``` //==========LoopScrollRect==========
        #if UNITY_EDITOR
        protected override void Awake()
        {
            base.Awake();
            if (Application.isPlaying)
            {
                float value = (reverseDirection ^ (direction == LoopScrollRectDirection.Horizontal)) ? 0 : 1;
                if (m_Content != null)
                {
                    Debug.Assert(GetAbsDimension(m_Content.pivot) == value, this);
                    Debug.Assert(GetAbsDimension(m_Content.anchorMin) == value, this);
                    Debug.Assert(GetAbsDimension(m_Content.anchorMax) == value, this);
                }
                if (direction == LoopScrollRectDirection.Vertical)
                    Debug.Assert(m_Vertical && !m_Horizontal, this);
                else
                    Debug.Assert(!m_Vertical && m_Horizontal, this);
            }
        }
        #endif```
Line 668 at `LoopScrollRectBase.cs`
