### ISSUE TITLE
Horizontal 布局 Slider 快速拉动会错误实例化 GameObject

### ISSUE THREAD

**Issue by LiuOcean** [qiankanglai/LoopScrollRect#138]
![image](https://user-images.githubusercontent.com/20659474/173807954-a274876d-f0ce-4689-a1bf-55ab5287daaa.png)

Unity 2021.3.4f1
图中是 Horizontal Grid 测试，初始设一个很大的 count，然后快速左右拉动 Slider 即可复现

**Comment by qiankanglai** [comment]
感谢，这个地方确实之前的判断方法有问题【当时为了处理只有一两个item情况下拖拽鬼畜情况，加了过于严格的判断，导致快速拉到头部或者尾部的时候就不回收了】
master分支最新已修复
