### ISSUE TITLE
Scroll Elements

### ISSUE THREAD

**Issue by jaydeep6492** [qiankanglai/LoopScrollRect#139]
I Just Want To Ignore Some Element For Pooling - Reusing In Scroll Content & Also Want To Use One Prefab To Pooling - Reusing In Same Scroll Content For That I Can't  Customize.

**Comment by qiankanglai** [comment]
>  Ignore Some Element For Pooling
I'm not sure whether these elements differs in content or not? From the description, I think you could just take one prefab for pooling, and customize `ProvideData`: the elements could take continunous index but provide discontinunous content instead.

**Comment by jaydeep6492** [comment]
Yes Elements are different from each other

**Comment by qiankanglai** [comment]
Sorry for not noticing the issue...

Different elements could be optimized with some object pool customization: just provide different prefab in [LoopScrollPrefabSource](https://github.com/qiankanglai/LoopScrollRect/blob/master/Runtime/LoopScrollPrefabSource.cs) with `index` provided.
