### ISSUE TITLE
It is impossible to jump to a particular index/item in the loopscrollrect

### ISSUE THREAD

**Issue by tammukul** [qiankanglai/LoopScrollRect#14]

**Comment by qiankanglai** [comment]
You need to implement it yourself.

**Comment by tammukul** [comment]
Do you have a snippet of code which will explain how to do this ?

Since the items are loaded/unloaded as we scroll, how can I scroll to a specific item ?

**Comment by qiankanglai** [comment]
There are two ways in convenience:

(a) add a coroutine for tween (for example move 20 pixels per second...and wait till the position you want). As you can get the child yourself, you know whether it is the right place to stop. However this is not elegant 😸 

(b) In fact I've already provided a method called `RefillCells` and offset is what you need. This method helps refill all cells starting from the specified count. For example `RefillCells(3)` meaning you have a LoopScroll with idx=3 as the first one.
But the pity is your don't have the animation now.

Just pick the method you want

**Comment by tammukul** [comment]
Thank you... this is really useful.

Thanks for documenting it too. Pretty sure lots of people will surely use it properly.

**Comment by qiankanglai** [comment]
https://github.com/qiankanglai/LoopScrollRect/blob/master/Images/ScrollToIndex.gif

new version for Scroll To Index (with coroutine)
