### ISSUE TITLE
LoopHorizontalScrollRectMulti.normalizedPosition计算问题

### ISSUE THREAD

**Issue by YaooQi** [qiankanglai/LoopScrollRect#143]
LoopHorizontalScrollRectMulti组件, 在onValueChanged的回调获取到normalizedPosition,  值的范围在 0 ~1.8
可以用UGUI的ScrollRect对比测试
![image](https://user-images.githubusercontent.com/51896267/179494455-cbdd4a7e-f1bc-400d-9a41-a52730ae5e18.png)

**Comment by qiankanglai** [comment]
这个一般是计算了错误的total size导致的，可否提供剥离的例子？

**Comment by YaooQi** [comment]
是因为LoopScrollRectBase的`GetHorizonalOffsetAndSize`和`GetVerticalOffsetAndSize`接口没有计算`contentSpacing`导致的,  这个问题你在4天前已经修复了.  我们项目使用的版本没有及时更新,  感谢!

**Comment by qiankanglai** [comment]
hhhh这块功能我之前没有大量测试，最近正好在Nova里重新接入的时候发现了就顺手修了~

[Issue#144](https://github.com/qiankanglai/LoopScrollRect/pull/144) 那边我测了下有点问题，直接在那边讨论吧

感谢
