### ISSUE TITLE
第一次生成item过多，滑动列表后恢复正常

### ISSUE THREAD

**Issue by BWMaple** [qiankanglai/LoopScrollRect#147]
@qiankanglai 你好，我最近在使用这个插件进行开发，但是遇到了点问题。
我做了一个竖垂直列表，内容由Title、Dock和Bean三种预制体构成，根据内容Bean会加入到Dock中，最多五个，可以正常循环。但是在一开始生成第一批内容的时候，会生成30个预制体，把内容的高度撑的很长，在内容滚动以后，高度会恢复到demo中的那种合适的高度，多余的预制体都会归还到池中，之后高度就一直正常，十分的奇怪。

**Comment by qiankanglai** [comment]
可以提供一个最简单例子么？
我之前遇到过有用户类似问题是: 一开始生成的时候loop scroll的scale=0 导致content size计算不对，但是滑动一下之后就正常了
