### ISSUE TITLE
排版不即时问题

### ISSUE THREAD

**Issue by alan49973028** [qiankanglai/LoopScrollRect#148]
我遇到的，主要是 Layout 不会即时排版，可能是 Layout 用太多层了(?)
导致计算子物件大小等，都不是非常正确，滚动时出现诡异的抖动
所以在子物件新增/删除之后，会呼叫 LayoutRebuilder.ForceRebuildLayoutImmediate(content)

**Comment by qiankanglai** [comment]
确实这个听起来是layout没有立刻刷新导致... 从LoopScrollRect角度来说，只管负责`LayoutUtility.GetPreferredWidth`调用获取，所以可以在`ProvideData`里强制刷一次，也可以实现`ILayoutElement`接口来直接提供相关信息(参考https://github.com/qiankanglai/LoopScrollRect/issues/140)

**Comment by alan49973028** [comment]
有参考那篇实现 ILayoutElement ，但强制刷新还是要做......

**Comment by alan49973028** [comment]
抱歉，再确认了一次。
是子物件的内容没有即时正确排版，造成视觉错误。子物件在content中是正确的。
所以LoopScrollRect基本上没问题，是子物件没有即时排版，造成还要强制刷新...
