### ISSUE TITLE
快速拖动scrollrect之后，导致不应该被移除的item被移除

### ISSUE THREAD

**Issue by junbinliuext** [qiankanglai/LoopScrollRect#149]
如gif所示快速拖动scrollrect(大概1~2帧)，会导致scrollrect排在前面的item被删掉了，然后导致scrollrect无法正常回弹。
![bandicam 2022-10-11 15-38-54-374 mp4_20221011_155029](https://user-images.githubusercontent.com/115531148/195032460-9aabb40c-9713-429b-81d9-8d7b23502f69.gif)

排查了一下原因，发现是LoopVerticalScrollRect的UpdateItems中，关于DeleteItemAtStart 和 NewItemAtEnd的时序不太对，应该先NewItemAtEnd再DeleteItemAtStart ，这样才能正确的触发DeleteItemAtStart中的Special Case，从而保证排在前面的item不被错误地删除。
![Snipaste_2022-10-11_16-18-41](https://user-images.githubusercontent.com/115531148/195037045-4c4458c2-bf92-4b6a-9235-0030b357235a.png)

按照上面说的反转两者的执行顺序，能够解决gif中的问题。

**Comment by qiankanglai** [comment]
抱歉由于项目太忙 没有及时反馈orz
问题确实存在，已按照建议修复，非常感谢！
