### ISSUE TITLE
scroll.RefillCells(int offset = 0)和scroll.RefillCellsFromEnd(int offset = 0)的offset 是更新起始位置的意思吗？

### ISSUE THREAD

**Issue by pengjoy** [qiankanglai/LoopScrollRect#15]
比如我插入了一个数据到Index_6，前面6个不更新，后面列表从这个6位置开始更新的意思是吗？
----
感觉
itemTypeEnd = reverseDirection ? offset : totalCount - offset;
这里的offset可以加一个保护

**Comment by qiankanglai** [comment]
是重新刷一遍数据，只不过显示上的第一个从6开始填数据
