### ISSUE TITLE
你好，怎么实现onscrollend啊，需要监听滚动停止时的回调

### ISSUE THREAD

**Issue by springlight** [qiankanglai/LoopScrollRect#154]

**Comment by qiankanglai** [comment]
我不太清楚具体滚动停止是指什么...
如果是松手事件，那么参考`IEndDragHandler`相关接口；如果是松手之后的自动滑动停止，那么可以看下`LateUpdate`，速度衰减到0的地方抛出事件即可

**Comment by springlight** [comment]
> 我不太清楚具体滚动停止是指什么... 如果是松手事件，那么参考`IEndDragHandler`相关接口；如果是松手之后的自动滑动停止，那么可以看下`LateUpdate`，速度衰减到0的地方抛出事件即可

谢谢回复，好迅速，我没表达清楚，我意思就是比如我松手之后，滚动列表还是会滚动对吧，我要的就是当列表滚动停止的时候，抛出去这个类似scrollend事件。我先用你给的思路试试
