### ISSUE TITLE
我在Loop Vertical Scroll Rect下面的Item高度设置比较高， 当我勾选了reverse direction 在滚动到边缘时，会突然的发生跳动

### ISSUE THREAD

**Issue by passerph** [qiankanglai/LoopScrollRect#155]
比如（3>4>5>6)会突然变成（4>5>6>7)，在移动到边缘某个位置时，会发生反复变化，正向的时候是ok的没有任何问题，还有一个问题，就是在勾选了 reverse direction后，拖动松手后的缓动，会突然变成反向滚动，请教一下是什么原因

**Comment by qiankanglai** [comment]
如果打开reverseDirection，需要设置下Content的锚点对应到另一侧的，可以参考下Demo场景
