### ISSUE TITLE
RefreshCells 刷新问题

### ISSUE THREAD

**Issue by 834153063** [qiankanglai/LoopScrollRect#157]
这个代码好像会导致数据紊乱，我这边有个项目，需要做分页查询，然后我现在的代码逻辑是第一次进来的时候先用初始化RefillCells这个代码，然后在获取到新增数据的时候调用RefreshCells这个代码，但是现在我在使用过程中出现了几个一个bug，我现在设定分页的量为2，然后经过6次分页之后数据变成了12个，然后疯狂拉动这个scroll的时候数据偶尔会变成只有2个，或者3个，或者其他个数，反正就是数量不对，然后还有可能会出现Transform child out of bounds这个错误
![1684768888994](https://github.com/qiankanglai/LoopScrollRect/assets/30400364/81e2ca23-0a76-4c69-8b7c-dc44c7a6ad24)

**Comment by 834153063** [comment]
欧，刚我看了下底层代码，发现好像不是RefreshCells的问题，而是在疯狂拖动的时候，数据更新上面的问题

**Comment by qiankanglai** [comment]
能剥离出一个例子么？我本地试图复现下

**Comment by 834153063** [comment]
> 

我对照Demo发现问题啦，是我没有在item添加Layout Element组件，加上之后就没问题了

**Comment by qiankanglai** [comment]
好~ 那我先关闭这个issue了，之后如果有别的问题欢迎交流
