### ISSUE TITLE
当列表滑动到最底部时   把 totalCount改为很小的值再调用 RefreshCells 会被清空列表

### ISSUE THREAD

**Issue by InMyBload** [qiankanglai/LoopScrollRect#158]
看代码 是 NewItemAtEnd 方法里面 itemTypeEnd的值 始终大于 totalCount  直接返回-1 无法创建造成的

**Comment by qiankanglai** [comment]
这个用法一开始就不在设计之中orz
如果涉及到修改totalCount，那么应该配合Refill（如果极端情况，需要保证位置不变，可以配合`RefillCells`里的参数设置）
而Refresh其实是在totalCount不变的情况下，单纯用来刷数据使用的

这个我得想想有没有好一些的方法给用户提示
