### ISSUE TITLE
发现一个疑似Bug的情况，详情如下

### ISSUE THREAD

**Issue by lifaxiang** [qiankanglai/LoopScrollRect#16]
正在做的需求是一个聊天，收到一条消息settotalcount，这样totalcount会每次加一，然后设置verticalNormalizedPosition缓动到1，这个时候会去检测顶部的item是否可以删除，检测viewBounds.max.y < contentBounds.max.y - threshold时为true，进入删除的时候有个判断(totalCount >= 0 && itemTypeEnd >= totalCount - 1)这里true了，导致顶部item一直删不掉。

**Comment by qiankanglai** [comment]
麻烦提供一个可复现的demo

**Comment by lifaxiang** [comment]
public class Test111 : MonoBehaviour {

    public LoopVerticalScrollRect _loop;
	// Use this for initialization
	void Start () {
        _loop.totalCount = 0;
	}
	
	// Update is called once per frame
	void Update () {
        if (Input.GetKeyDown(KeyCode.Space))
        {
            _loop.totalCount += 1;
            _loop.verticalNormalizedPosition = 1;
        }
	}
}


加这个脚本就可以看到问题，您试试，我用这个复现了

**Comment by qiankanglai** [comment]
抱歉周末没有及时处理。我查了下确实存在这个问题，已经加了保护修复。

这里的思路是**在移动过程中**，如果已经到尾部的时不能直接删掉头部，不然会导致抖动(这种情况会在元素不够，没法撑满一屏的时候发生)

**Comment by lifaxiang** [comment]
好的，非常感谢，辛苦了！
