### ISSUE TITLE
当列表内有元素时，应用程序失去焦点，列表内容有时会莫名奇妙的被全部回收

### ISSUE THREAD

**Issue by NicoIer** [qiankanglai/LoopScrollRect#166]

**Comment by NicoIer** [comment]
排查了一下，应该是，在拖动过程中，失去焦点会导致异常

**Comment by NicoIer** [comment]
![image](https://github.com/qiankanglai/LoopScrollRect/assets/91652330/6e703c0d-f130-4cd0-857e-065eae91a8a7)

**Comment by NicoIer** [comment]
[video.zip](https://github.com/qiankanglai/LoopScrollRect/files/14155667/video.zip)
这里是一段录屏

**Comment by NicoIer** [comment]
![image](https://github.com/qiankanglai/LoopScrollRect/assets/91652330/621cb7e8-343d-48b8-9ea1-7598c4c2fbdd)
删除列表中Item的位置在这里

**Comment by NicoIer** [comment]
是因为我修改了这里RectTransform的锚点导致的异常么？
![image](https://github.com/qiankanglai/LoopScrollRect/assets/91652330/bcd1a4d8-4300-41fe-9972-eb7e12e0e137)

**Comment by NicoIer** [comment]
毫无疑问的是，当播放时，如果列表中有Item，点击暂停按钮，列表中的Item都会被删除

**Comment by qiankanglai** [comment]
不好意思前段时间休假 没能及时回复

> 是因为我修改了这里RectTransform的锚点导致的异常么？

这里可以检查下外层的ChatPanel节点大小是否固定，我怀疑是这块有问题：主要检查下ScrollRect的本身大小是否稳定；此外还可以看下Content这个节点，垂直列表的情况应该是(0.5,1)或(0.5,0)。

或者也可以用DemoScene里的场景试一下？我本地测试失焦/暂停情况下都是正常的。

**Comment by NicoIer** [comment]
> 不好意思前段时间休假 没能及时回复
> 
> > 是因为我修改了这里RectTransform的锚点导致的异常么？
> 
> 这里可以检查下外层的ChatPanel节点大小是否固定，我怀疑是这块有问题：主要检查下ScrollRect的本身大小是否稳定；此外还可以看下Content这个节点，垂直列表的情况应该是(0.5,1)或(0.5,0)。
> 
> 或者也可以用DemoScene里的场景试一下？我本地测试失焦/暂停情况下都是正常的。

大概率是因为`聊天Item`的`layoutelemt`没有指定`PerrfitHeight`导致的
我使用了UGUI的布局组件来让`聊天Item`的高度随`聊天内容`来动态改变，因此没有办法在编辑器下指定`聊天Item`的perrfitHeight。
或许根据`聊天Item`的高度在代码中动态设置`perrfitHeight`能够解决这个问题?我之后来试一下

**Comment by qiankanglai** [comment]
LoopScrollRect确实依赖PreferredHeight来计算需要多少个元素能填满，可以改下试试
