### ISSUE TITLE
RefillCellsFromEnd刷新，没有预期把列表弹回底部

### ISSUE THREAD

**Issue by tangjialang** [qiankanglai/LoopScrollRect#167]
只是把最底部的go加载了出来，位置似乎有点问题
![image](https://github.com/qiankanglai/LoopScrollRect/assets/42792101/75f641b3-b25e-479c-be56-9807a521c9fb)
[LoopScroll-RefillCellsFromEnd-Bug.zip](https://github.com/qiankanglai/LoopScrollRect/files/14393733/LoopScroll-RefillCellsFromEnd-Bug.zip)
示例工程使用Unity 2021.3.25f1c1
分辨率1080*1920没做适配哈

**Comment by qiankanglai** [comment]
我看了下工程，主要是ScrollView的布局正好做成**上下颠倒**的了...
![1709461980526](https://github.com/qiankanglai/LoopScrollRect/assets/1546130/eb666ab7-8b2b-4d7d-9ca3-7e9059168a73)

我改成这样的
![1709462015297](https://github.com/qiankanglai/LoopScrollRect/assets/1546130/5ccf336a-e026-4e1e-a8de-b766e7e15736)

测了下没问题了~ 核心还是ScrollView这层的布局确保正确，如果使用上需要内容是颠倒的，可以参考sample工程里的`VerticalScroll_Reverse`使用

**Comment by qiankanglai** [comment]
msg这个元素实际高度是100，但是Layout Properties里认为是71.45
![1709464791210](https://github.com/qiankanglai/LoopScrollRect/assets/1546130/b0d827ce-98e8-4efa-925c-aa98e54723f2)

解决办法可以参考Sample工程做法，挂一个Layout Element然后强制Preferred Height是100（和实际高度保持一致）即可
![1709464875021](https://github.com/qiankanglai/LoopScrollRect/assets/1546130/a283e5a4-7f2d-4d22-8e1b-cfb2acee1b68)
