### ISSUE TITLE
awake调用RefillCellsFromEnd然后使用start再次调用会造成了content的不正确偏移

### ISSUE THREAD

**Issue by tangjialang** [qiankanglai/LoopScrollRect#168]
不在awake调用RefillCellsFromEnd不会有问题
![image](https://github.com/qiankanglai/LoopScrollRect/assets/42792101/b785577a-2f9f-4a0c-a36f-0db3a4e12988)

[LoopScroll-Awake-Start-Call-RefillCellsFromEnd-Bug.zip](https://github.com/qiankanglai/LoopScrollRect/files/14393791/LoopScroll-Awake-Start-Call-RefillCellsFromEnd-Bug.zip)
版本 2021.3.25f1c1
分辨率 1080*1920

**Comment by qiankanglai** [comment]
和 https://github.com/qiankanglai/LoopScrollRect/issues/167 一样的问题，我本地改了下ScrollView这个节点之后表现正常

**Comment by qiankanglai** [comment]
首先和 https://github.com/qiankanglai/LoopScrollRect/issues/167 一样，需要msg上挂一个LayoutElement(PreferredHeight=100)

这个地方确实有时序问题：`Test::Awake`调用的时候，`LoopVerticalScrollRect::Awake`确实还没调用到，导致`direction`变量没有准备好。
感谢指出~ 已修复
