### ISSUE TITLE
Missing documentation how to use 'LoopScrollDataSource'

### ISSUE THREAD

**Issue by Baterka** [qiankanglai/LoopScrollRect#17]
Hi, I need help how to use `LoopScrollDataSource`. Indexes working well but where I can fill `objectsToFill`?
I need pass some other variables to my Prefab

**Comment by qiankanglai** [comment]
There are two ways. The first one is for compatibility

    loopScrollRect.objectsToFill = new string[]{"a", "b"};

The second one is for general usage:

    loopScrollRect.dataSource = new LoopScrollArraySource<string>(new string[]{"a", "b"})
