### ISSUE TITLE
Scrolling does not work well when the height of the Cell is larger than the display area

### ISSUE THREAD

**Issue by ynaoto** [qiankanglai/LoopScrollRect#173]
Scrolling does not seem to work well when the height of the Cell is larger than the display area. The scrolling does not continue even when swiping, and it behaves as if it is trembling. This is especially noticeable when operating with the mouse in the Unity Editor. When operated with a smartphone, it behaves as if it “escapes” such a state by taking a large swipe. If this is difficult to fix, is there any workaround?

**Comment by qiankanglai** [comment]
Hi, I tried to reproduce with existing demo but failed. (RectMask2D is disabled for debug)
![screenshot-20240611-210922](https://github.com/qiankanglai/LoopScrollRect/assets/1546130/8d9b01b3-99c6-4bf6-8617-12b036858ef8)

Could you provide a small example so I can investigate this problem.

**Comment by ynaoto** [comment]
This was my mistake. The cause was that I was getting the information needed for ProvideData asynchronously. I solved the problem by changing it so that information required for layout is obtained ahead of time. Sorry for the trouble. I will close it.
