### ISSUE TITLE
Problem with scroll

### ISSUE THREAD

**Issue by vandelpal** [qiankanglai/LoopScrollRect#18]
I use dynamically filled horizontal list, update DataSource and scroll to need position. But the scroll does not behave correctly!
Using a demo it can be shown so:

    public class InitOnStart : MonoBehaviour
    {
        void Start()
        {
            var loop = GetComponent<LoopScrollRect>();
            loop.totalCount = 5;
            loop.RefillCells();
        }

        void Update() {
            if (Input.GetKeyDown(KeyCode.Space)) {

                var loop = GetComponent<LoopScrollRect>();
                loop.totalCount += 10;
                loop.RefillCells();
                loop.horizontalNormalizedPosition = 1;
            }
        }
    }

Afte press Space, List increase size to 15 elements, scroll to end, and immediately scroll to begin!! Why scroll to begin? I set horizontalNormalizedPosition  to 1 that should be end of list!

here it works correctly: 

    public class InitOnStart : MonoBehaviour {
        private int count = Int32.MaxValue;

        void Start() {
            var loop = GetComponent<LoopScrollRect>();
            loop.totalCount = 5;
            loop.RefillCells();
        }

        void Update() {
            if (Input.GetKeyDown(KeyCode.Space)) {
                var loop = GetComponent<LoopScrollRect>();
                loop.totalCount += 10;
                loop.RefillCells();
                count = 0;
            }
            if (count < 3) {
                GetComponent<LoopScrollRect>().horizontalNormalizedPosition = 1;
                count++;
            }
        }
    }

But if change condition to if (count < 2)  - not work).  For more items need more count.
what happen??

**Comment by qiankanglai** [comment]
Got it. I'll check & fix this weekend (quite busy these days...

**Comment by vandelpal** [comment]
Ok, thanks! I also think the methods 
LoopVerticalScrollRect->ScrollToItem(int itemIndex, VAlign align) 
LoopHorizontalScrollRect->ScrollToItem(int itemIndex, HAlign align) 
will be very useful.

**Comment by qiankanglai** [comment]
Hey @vandelpal , I've fixed a this bug: updateItems will make normalizedPosition change a little, so move happens. Now the script you provided works well.

For `LoopVerticalScrollRect->ScrollToItem(int itemIndex, VAlign align)`, as I mentioned in https://github.com/qiankanglai/LoopScrollRect/issues/14, it is a little complex for me to implement this directly into LoopScrollRect. For my own projects, I make movement with the help with DOTween in fact

**Comment by vandelpal** [comment]
This fix added overhead, my lists started freeze! 
If you add time checker for this:
 
if (Input.GetKeyDown(KeyCode.Space)) {
                var loop = GetComponent<LoopScrollRect>();
                loop.totalCount += 100;
                loop.RefillCells();

                stopWatch = new Stopwatch();
                stopWatch.Start();
                loop.horizontalNormalizedPosition = 1;
                stopWatch.Stop();

                long time = stopWatch.ElapsedMilliseconds;
                Debug.Log(String.Format("{0} = {1}ms", tag, time));
            }

And press Space 8 times, you will see:
Growing pool ScrollCell3: 6 populated
Growing pool ScrollCell3: 12 populated
Growing pool ScrollCell3: 24 populated
Growing pool ScrollCell3: 48 populated
Growing pool ScrollCell3: 96 populated
Time = 56ms
Growing pool ScrollCell3: 192 populated
Time = 66ms
Time = 99ms
Growing pool ScrollCell3: 384 populated
Time = 158ms
Time = 179ms
Time = 227ms
Time = 291ms
Growing pool ScrollCell3: 768 populated
Time = 451ms

This time 450ms on my PC corei7  it is too long. But if change line to 

stopWatch.Start();
 loop.horizontalNormalizedPosition = 0f;
stopWatch.Stop();

You will see:
Time = 0ms
Time = 3ms
Time = 2ms
Time = 2ms
Time = 2ms
Time = 2ms
Time = 2ms
Time = 2ms
Time = 1ms
And don't see message about Growing pool. 
I used scroll that viewed only 4 elements, why pool grow so much?

All this procedure should be a simple transpositionand not take time on yourself. Now something is happening globally and hard. The work of the LoopScrollRect is not optimized :(

P.S. The code without this fix have bug, but works not so slow.

**Comment by qiankanglai** [comment]
Because you are using "RefillCells" which means from start to end. After 8 space, when you call `loop.horizontalNormalizedPosition = 0f;` you are moving excatly from the first one to the last one (800 cells)..

For your case, I highly suggests you using ` loop.RefillCellsFromEnd(); ` which fill cells from end 😸

**Comment by qiankanglai** [comment]
This is why I haven't find a good way to implement `ScrollToItem`... For now this component only supports moving cell by cell, or jump directly. It is quite easy to mis-use these APIs...

**Comment by vandelpal** [comment]
Now I replaced LoopScrollRect to EnchancedScroller ( https://www.assetstore.unity3d.com/en/#!/content/36378 ). All works perfectly! No freeze, have method for scrollItem, pure code.
P.S. This plugin can be found for free on the Internet ;)

**Comment by qiankanglai** [comment]
Glad you solved this. Also please respect others' work and code.
