### ISSUE TITLE
一个咨询问题

### ISSUE THREAD

**Issue by MonsterZhangChen** [qiankanglai/LoopScrollRect#180]
请问一下，目前LoopScrollRect在商业项目中运行稳定的先例吗。我们项目组准备迁移这个强大的组件

**Comment by qiankanglai** [comment]
我们自己之前上线的若干项目都有在用（翻了下提交记录居然9年前了orz）后面主要也就修修补补了

其它公司商业项目有时候看包体dll能看到，但是到底用没用我也一直没高兴统计orz

**Comment by MonsterZhangChen** [comment]
了解了，谢谢！
