### ISSUE TITLE
Trying to remove base_model (UnityEngine.UI.Image) from rebuild list while we are already inside a rebuild loop. This is not supported.

### ISSUE THREAD

**Issue by kebingbing** [qiankanglai/LoopScrollRect#19]
Trying to remove base_model (UnityEngine.UI.Image) from rebuild list while we are already inside a rebuild loop. This is not supported.
UnityEngine.GameObject:SetActive(Boolean)
UnityEngine_GameObjectWrap:SetActive(IntPtr) (at Assets/ToLuaGenerate/UnityEngine_GameObjectWrap.cs:296)
LuaInterface.LuaDLL:lua_pcall(IntPtr, Int32, Int32, Int32)
LuaInterface.LuaState:PCall(Int32, Int32) (at Assets/LuaFramework/ToLua/Core/LuaState.cs:632)
LuaInterface.LuaFunction:PCall() (at Assets/LuaFramework/ToLua/Core/LuaFunction.cs:91)
UnityEngine.UI.LoopScrollRect:LateUpdate()
unity版本5.4.3  
出现问题的情况 是我操作克隆出来的item 里面的元素  隐藏里面的image  就会出现这个错误

**Comment by qiankanglai** [comment]
这个是因为循环触发rebuild了，最简单的解决办法是等下一帧再刷新数据

**Comment by kebingbing** [comment]
嗯，谢谢

**Comment by kebingbing** [comment]
还有一个问题 就是在使用该插件的时候  如果我们item 里面有异步操作比如异步加载图片  定时器 等  item 滑出去以后  没有通知  不能关掉定时器  会出现一些问题    可以添加一个item 回收通知

**Comment by qiankanglai** [comment]
你监听下ScrollCellReturn消息就行了，这个是有的

**Comment by kebingbing** [comment]
protected float DeleteItemAtEnd()
        {
            if (((m_Dragging || m_Velocity != Vector2.zero) && totalCount >= 0 && itemTypeStart < contentConstraintCount) 
                || content.childCount == 0)
            {
                return 0;
            }

            float size = 0;
            for (int i = 0; i < contentConstraintCount; i++)
            {
                RectTransform oldItem = content.GetChild(content.childCount - 1) as RectTransform;
                size = Mathf.Max(GetSize(oldItem), size);

                if (reverseDirection == false)
                {
                    itemTypeEnd--;
                    ReturnObjectAndSendMessage(oldItem, itemTypeEnd);
                }
                else
                {
                    
                    ReturnObjectAndSendMessage(oldItem, itemTypeEnd);
                    itemTypeEnd--;
                }

这个是我稍微改过一下的代码  以前的代码  itemTypeEnd-- 没有判断reverseDirection  会出现出去的对不上号

**Comment by qiankanglai** [comment]
收到，非常感谢

**Comment by kebingbing** [comment]
应该谢谢你

**Comment by SunnyShao** [comment]
作者大大，想问下为什么会出现这种情况呢，大多数的时候隐藏物体是不会出现这个错误的，偶尔会出现这个问题

**Comment by qiankanglai** [comment]
这个情况我在代码里应该是保护掉了，如果只是隐藏物体不是删除的话应该不会发生。如果最新的代码还是有这个情况的话，麻烦能不能剥离一个例子，我来解决一下~
