### ISSUE TITLE
添加EventTrigger组件之后无法滑动

### ISSUE THREAD

**Issue by xiaofeihujj** [qiankanglai/LoopScrollRect#20]
你好！最近在使用的时候，需要在cell上添加EventTrigger组件，结果无法滑动了，查了下，原因是EventTrigger继承了Drag的几个接口，导致LoopScrollRect里的Drag方法无法接受监听，那么有什么方法解决呢？谢谢！

**Comment by qiankanglai** [comment]
非常不好意思回复的太晚了...
简单的做法就是在EventTrigger上把事件抛给LoopScrollRect，你可以把onDrag那几个接口暴露出来之后直接调用
