### ISSUE TITLE
ContentSizeFitter and grid performance issue.

### ISSUE THREAD

**Issue by jannysice** [qiankanglai/LoopScrollRect#23]
Using Content size fitters and grid layout groups together with scroll rect or loopscroll results in the UI Updating all the time. Even when nothing in the UI changes/the scroll doesn't move. Disabling the content size fitter resolves this issue but then scrolling doesn't work as intended anymore. I tried to make the scrolling work without a content size fitter, but I didn't manage to pull it off.  
![profilergraph](https://user-images.githubusercontent.com/25015941/32847803-4832d864-ca2b-11e7-846a-05278a1a5509.PNG)
![profilerdata](https://user-images.githubusercontent.com/25015941/32847813-4db67214-ca2b-11e7-8643-0aa78a558a43.PNG)

Is there a way to use loopscroll with a grid and without a content size fitter?

**Comment by qiankanglai** [comment]
Can you provide a sample for it? I just profile the case without move and it seems fine...

![image](https://user-images.githubusercontent.com/1546130/32869339-622bde88-cab1-11e7-834d-660a151dd50f.png)
