### ISSUE TITLE
Use with my own pool

### ISSUE THREAD

**Issue by Try4W** [qiankanglai/LoopScrollRect#25]
When I trying to replace included `Pool` with simple Instantiate/Destroy `ScrollRect` is going crazy :)
Later I want to use `Adapter` to simply integrate any pooling manager, like Zenject etc.

Any advice?
Thanks!

**Comment by Try4W** [comment]
You can check my sample project with single `Adapter` instead of `DataSource&PrefabSource`:
[LoopScrollRect-master.zip](https://github.com/qiankanglai/LoopScrollRect/files/1489432/LoopScrollRect-master.zip)

**Comment by FullStackForger** [comment]
Check with @qiankanglai  but it might be better if you did PR @Try4W so it can be merged into the project.

**Comment by qiankanglai** [comment]
sorry for missing the reply. I'll check do ASAP

**Comment by qiankanglai** [comment]
Hey @Try4W , your implementation works fine 👍  but I still prefers the current style. Since our projects also use this plugin and we do need to separate Prefab & Data from each other.

I suggest if you could maintain a fork to provide another option.

**Comment by Try4W** [comment]
> your implementation works fine

nope :)

There is a problem with my sample project as `LoopScrollRect` getting laggy and starting strangely count ids.
It seems that` LoopScrollRect` won't work with any other pool(or simply Instantiating/Destroying) except the one provided out of the box.

I looking for solution to this problem :)
Any advice?

**Comment by qiankanglai** [comment]
Hi @Try4W , I rechecked your sample with Profiler and  `Instantiate(CellPrefab)` & `Destroy(go)`, will consume a lot. That is why I implement pool here.

You could try other pool policy in fact. In our projects, we have three different pool policies:
- Instantiate & Destroy: This is not quite often used but when we need reset properties after use, we may choose this. (eg. a prefab with a lot of animations & particle systems, which will be messed up after playing)
- Pool with setting transform.parent: This is the most often used policy, like here.
- Pool with setting active: This is used when OnTransformChanged consumes a lot.

You might try and profile to find the most suitable one 😸

**Comment by Try4W** [comment]
Most noticeable fps drops&lags are happened not because of Instantiate() method
![image](https://user-images.githubusercontent.com/5736157/34024443-30d76e72-e15b-11e7-982d-e92c1fe1a6d6.png)

In fact, `Instantiate&Destroy` is pretty fast by my experience.

As far as I can tell, there is a problem in `ScrollRect` implementation. I simply replaced built-in `Pool` with `Instantiate&Destroy` which should work, but it isn't :)

It should work with simple `Instantiate&Destroy`, otherwise, your library depends on concrete game object provider implementation with is bad.

Also, If you will try to scroll to the most top item and then to the most bottom — offscreen elements won't be destroyed and id's starts to count strangely.
![image](https://user-images.githubusercontent.com/5736157/34024567-f9e6ca06-e15b-11e7-8599-8c425b0e554f.png)

It looks like a bug :)
Ask me if any additional information will be is needed.

**Comment by qiankanglai** [comment]
Hi @Try4W , the bug is very easy to find: You have to use **DestroyImmediate** here in FreeItem


        public override void FreeItem(GameObject go)
        {
            DestroyImmediate(go);
        }

Or this item will be freed with **Destroy** in next frame. So when we need `DeleteItemAtEnd` several times in one frame, it only frees the single last item several times

**Comment by qiankanglai** [comment]
Also I just modified code a bit to prevent useless UpdateItem. But profiler shows still UpdateLayout consumes a lot.
In fact I've considered replacing this (since this comes from the origin UGUI ScrollRect): if we don't need auto layout and every cell can compute its own size, we are able to save this but it will break the UGUI auto layout function.
