### ISSUE TITLE
LoopScrollRect 在安卓上滑动时会出现卡顿，请问有啥方法解决么

### ISSUE THREAD

**Issue by FatQuan** [qiankanglai/LoopScrollRect#26]
LoopScrollRect 在安卓上滑动时会出现卡顿，请问有啥方法解决么

**Comment by qiankanglai** [comment]
能否提供一个可运行的demo

**Comment by FatQuan** [comment]
请原谅我不能给你demo，因为我们这个项目在开发期中。所以暂时不能公开

**Comment by FatQuan** [comment]
我们游戏打包到安卓的时候，进入主页fps为38，打开排行榜（loopscrollrect）的时候fps降到28，滑动的时候fps为15。所以在安卓上不怎么流畅。但是苹果手机上是没有问题的

**Comment by FatQuan** [comment]
如果你有解决方案的话，请回复我，小弟在此谢过

**Comment by qiankanglai** [comment]
我的意思是能不能剥离一个最小可复现demo，或者最起码Profiler数据提供一下
因为这个控件我们用了好几个项目，没有遇到这么严重的帧率影响...
