### ISSUE TITLE
新功能建议

### ISSUE THREAD

**Issue by ZhaoXiangXML** [qiankanglai/LoopScrollRect#27]
1、建议增加一个Snap To Grid选项，使每次拖拽结束之后都会慢慢停到某个格子开始的地方
2、建议增加一个ScrollToItemAnimated方法，用于以一定的速度滚到某个格子

**Comment by qiankanglai** [comment]
第二个之前也有提到 https://github.com/qiankanglai/LoopScrollRect/issues/14
这个最大的问题是不好封装，我们自己项目使用的时候是用dotween做的...等我忙完这阵子再好好想想
如果有PR也很欢迎

**Comment by ZhaoXiangXML** [comment]
用dotween怎么确定要移动多少个像素呢？

**Comment by qiankanglai** [comment]
因为我们使用场景中每个Cell大小和Padding是固定的，所以可以很方便的计算出来

**Comment by ZhaoXiangXML** [comment]
问题就是大小不固定的时候怎么办……

**Comment by ZhaoXiangXML** [comment]
要不然先把路上需要的全部初始化出来，反正动画的过程中需要显示……

**Comment by qiankanglai** [comment]
emmm 这是一个思路，但是和我之前的设计原则有点冲突...
这段时间我忙公司版本，要1月份的时候好好琢磨下。。。

**Comment by qiankanglai** [comment]
滑动功能我做了个coroutine版本，已上传（目前是匀速，有其他变速需求自己改下就行）

https://github.com/qiankanglai/LoopScrollRect/blob/master/Images/ScrollToIndex.gif

snap这个建议还是根据项目手感自己实现，因为我之前在不同游戏就做过不同版本的衰减函数，实在是难以统一
