### ISSUE TITLE
RefillCellsFromEnd 定位和滚动问题

### ISSUE THREAD

**Issue by carlosCn** [qiankanglai/LoopScrollRect#28]
实际需求中经常要插入之后，定位在列表的最后一个，发现两个问题：
1. RefillCellsFromEnd 接口不能很好让列表滚动到最后一个，不知道是不是位置计算问题
![image](https://user-images.githubusercontent.com/5885142/34340778-5adec676-e9c5-11e7-920b-85c7ebb64d98.png)
修改之后Ok
2. RefillCellsFromEnd 使用之后很大的概率很产生向上的的滚送（m_Inertia开启）， 估计是因为后面lateupdate的计算认为这是一个下拉的操作吧，我处理方式比较死，在这个函数最后 等待一帧，停止滚动
![image](https://user-images.githubusercontent.com/5885142/34340816-f8ac1fe8-e9c5-11e7-9511-2f183c0d8f66.png)

这里应该可以有更好的方式处理，

kanglai同学不知道能否从更好的方式优化下或者说本身我就在错误的方式使用？

**Comment by qiankanglai** [comment]
1. Demo场景和我们自己使用中没有发现类似问题，能否提供一个精简的可复现Sample，也许是一些边界情况我没处理到
2. 尝试在RefillCellsFromEnd之后调用一下UpdatePrevData然后StopMovement试试？或者能否发一个sample给我研究下

**Comment by lopezycj** [comment]
这个BUG我遇到了，我做界面的时候，上层有个UI的Canvas的scale变成了0，0，0，造成了LoopScrollRect里GetBounds计算出问题了，m_Content.GetWorldCorners这函数得到的m_Corners都是0。很诡异出现的

**Comment by yudixiaok** [comment]
问一下为什么没有封装 Add Insert Remove 这些通用的接口呢？

**Comment by qiankanglai** [comment]
因为现在Cell是靠连续index定位的，如果Insert/Remove的话就会乱了

**Comment by yudixiaok** [comment]
hi 可以给一个im 的联系方式吗？ 有些技术问题想探讨一下！
