### ISSUE TITLE
滚动条问题

### ISSUE THREAD

**Issue by hsl9999** [qiankanglai/LoopScrollRect#29]
好奇怪，我动态加入 item 到 content下，如果绑定 滚动条控件，数量一多就卡暴了？怎么回事呢？但如果没有绑定滚动条，一切都正常。

**Comment by qiankanglai** [comment]
麻烦提供一个最小复现demo

**Comment by hsl9999** [comment]
不好意思，认真检查下是自己的问题。把滚动的Steps设置太大了，导致跳太厉害，感觉卡了，改成1正常了。谢谢。
