### ISSUE TITLE
Scrollbar(Bug)

### ISSUE THREAD

**Issue by Avatarchik** [qiankanglai/LoopScrollRect#3]
Hi!How to use it?It considers all the elements and not only those which are visible on the screen,
Scrollbars should depend on the total Count

**Comment by qiankanglai** [comment]
well, I have to say scrollbar is not correctly implemented yet.
It is hard to do this without more constraints (like the size of elements out of screens), so I'm not aware of it yet :(

**Comment by qiankanglai** [comment]
Sorry for very late reply...After a long struggle, I managed to implement scrollbar in https://github.com/qiankanglai/LoopScrollRect/commit/5104ca92170b6371288c2706f9984e011cf7e9b2

I've updated new README with demos.
