### ISSUE TITLE
item的高度大小不规则，会导致出错

### ISSUE THREAD

**Issue by FatQuan** [qiankanglai/LoopScrollRect#32]
![image](https://user-images.githubusercontent.com/32729017/34703053-f0924a46-f52b-11e7-9fc4-6177db462348.png)

我这个功能是一个聊天的功能，用到了loopscrollrect 。但是当content底下的item高度为不规则的时候会出现item下的节点丢失的情况。

**Comment by qiankanglai** [comment]
麻烦提供一个最小可复现demo
