### ISSUE TITLE
可移植性替换方案

### ISSUE THREAD

**Issue by huangxianhui001** [qiankanglai/LoopScrollRect#33]
在LoopScrollRect的'ReturnObjectAndSendMessage'方法中,用到了ResourceManager,这里有点耦合,如果有自己的对象池实现方法,不用例子里自带的这个ResourceManager,这里会报错.发现获取对象池里的对象是通过LoopScrollPrefabSource这里拿的,那么也可以把对象回收方法也交由这个类来执行,那么ReturnObjectAndSendMessage这里就可以使用prefabSource的回收对象池方法了.一点建议,这个库还是挺好用的!

**Comment by qiankanglai** [comment]
非常感谢，已提交整理过的代码
