### ISSUE TITLE
求问能否将Easy Object Pool替换成PoolManager?

### ISSUE THREAD

**Issue by chaoshishouzhi** [qiankanglai/LoopScrollRect#34]
我尝试将Easy Object Pool替换成PoolManager，但是发现在将上下超范围的item返回池中时（这个动作在poolManager，我使用spawnPool.Despawn），索引会发生错乱，能否在这个问题给我一些帮助?

**Comment by chaoshishouzhi** [comment]
这是替换返回池中的时候：
private void ReturnObjectAndSendMessage(Transform go)
        {
            go.SendMessage("ScrollCellReturn", SendMessageOptions.DontRequireReceiver);
            //ResourceManager.Instance.ReturnObjectToPool(go.gameObject);
			
			m_CurPool.Despawner(go)

        }

**Comment by qiankanglai** [comment]
具体PoolManager里的代码贴一下~

**Comment by chaoshishouzhi** [comment]
已经找到原因了，是计算的时候没有找准位置，单单以poolmanager内部存储的顺序作为物理顺序了。感谢提供很好的优化方法。
