### ISSUE TITLE
cell点击事件如何传递到控制器

### ISSUE THREAD

**Issue by huangxianhui001** [qiankanglai/LoopScrollRect#36]
我们使用的是MVC结构,有个主控制器脚本,控制页面上所有UI元素,所有UI逻辑跳转都在这里处理,然后在cell上也绑定了一个脚本,用于控制该cell的显示,然后点击cell时,需要将点击事件传回给控制器,并告知下标,请问这个该如何实现,你的Demo中也没有这个功能.另外,如果我要设置某个cell的高亮状态,这个也没办法实现,希望下个版本能增加这个功能,谢谢!

**Comment by mosluce** [comment]
@huangxianhui001 我的作法是在場景中加入 ViewModel (ex. MyViewModel) ，並且把資料和狀態存放在 ViewModel 中，這樣你說的 Controller 就可以用直接獲取 ViewModel 並得知狀態，不過這個 Lib 我個人覺得比較不合理的是，Item 自己本身必須去抓取資料 (目前還沒寫出用 Controller 塞資料或綁定到 ViewModel 的作法)
所以我在 Item 中會用 Find("MyViewModel").GetComponent<MyViewModel>()  取得 ViewModel 進而得知狀態和資料

**Comment by huangxianhui001** [comment]
又是 find, 又是 getComponent 的,不会影响性能吗,我们主程不让这么写😂。后面我改了一下,给 cell 脚本定义一个基类,然后改了 prefabSource的 GetObject方法, 在这里获取基类脚本,绑定事件
`
 GameObject go = SG.ResourceManager.Instance.GetObjectFromPool(prefabPath,prefabPoolName);
            if (clickFun != null)
            {
                //添加点击事件
                LoopScrollRectCell cell = go.GetComponent<LoopScrollRectCell>();
                cell.OnClick.RemoveAllListeners();
                cell.OnClick.AddListener(clickFun);
            }
return go;`
至于那个 clickFun, 是loopscrollrect 的一个变量,由控制器传入的,所以改动还是挺大的,不知道作者大大有没有什么更解耦的方法

**Comment by qiankanglai** [comment]
不好意思前段时间出去旅游了没带电脑

@huangxianhui001 你的做法是可以。我之所以这么写的主要原因是不希望提供太多的限制，只提供最基础的消息机制；根据你们项目需要自定义一下会更好（实际上我们自己的项目也是类似的做法，不过和我们自己的一大套框架结合了起来，不好剥离）这个repo本质上只提供了核心的ScrollRect功能~

@mosluce 我们有一个项目是MVVM的，基于uFrame的一套(每个Cell对应的是一个View，然后绑定数据源) 但是理由同前...我可以给出一些思路参考，但是最后还是根据你们项目特点找到合适的方式来处理。。。不管我怎么封装总有人会觉得不顺手，所以我就尽可能只做最简单的处理~反正全套代码开源，你有什么想法完全可以自己实现~

**Comment by Eric0625** [comment]
为什么不直接在ScrollCellIndex里添加AddListener，在ScrollCellReturn里添加RemoveAllListeners呢？这样不用改任何源代码。会有什么副作用吗？

**Comment by qiankanglai** [comment]
可以这么干，我们自己的代码用了类似的思路
目前这部分我已经剥离出来，有需要的话大家按照各自顺手的写法改就行了
