### ISSUE TITLE
ResourceManager发现一处游戏对象未销毁

### ISSUE THREAD

**Issue by huangxianhui001** [qiankanglai/LoopScrollRect#37]
resourceManager 的InitPool方法里,创建了一个 gameObject, 供对象池做预设,但是最后没有销毁掉,导致场景中多了一个无用的游戏对象,可以在对象池初始化完毕后,销毁掉该对象

**Comment by qiankanglai** [comment]
这个对象池不能销毁，因为初始化之后还要不断使用... 譬如有个Scroll里释放掉的东西要塞回去

**Comment by huangxianhui001** [comment]
我说的是你的ResourceManager第48-55行这边,
`GameObject pb = Resources.Load<GameObject>(poolName);
                if (pb == null)
                {
                    Debug.LogError("[ResourceManager] Invalide prefab name for pooling :" + poolName);
                    return;
                }
                poolDict[poolName] = new Pool(poolName, pb, gameObject, size, type);`
这里的 pb在传到 Pool 的初始化方法里后,就没用了.而且在每初始化一个对象池,在Unity 的 Hierarchy 面板就会多一个游戏对象,就是这边生成的 pb, 所以应该把这个销毁掉,

**Comment by qiankanglai** [comment]
这里不销毁也会被自动回收的，因为没有指向它的引用了...
