### ISSUE TITLE
格子控件问题

### ISSUE THREAD

**Issue by wumiliu** [qiankanglai/LoopScrollRect#4]
当格子的每行个数为4的时候，如果初始格子为3个，后面修改为50 个或者更多。超过一屏。
这时候，会发现格子数量有问题。
![tmp](https://cloud.githubusercontent.com/assets/6247904/17956709/662a8c40-6abe-11e6-81de-5d3eb3ab60e4.jpg)

**Comment by wumiliu** [comment]
修改NewItemAtEnd函数
![bug](https://cloud.githubusercontent.com/assets/6247904/17956730/7f8bb8f8-6abe-11e6-88f4-f42ad3e56291.jpg)

**Comment by qiankanglai** [comment]
我周末抽空测试下

或者要是方便的话直接提交Pull Request吧 :smile:

**Comment by qiankanglai** [comment]
https://github.com/qiankanglai/LoopScrollRect/commit/753ab705f56873b4369feab8de42b0259e58310c 
代码已修复，多谢！
