### ISSUE TITLE
初始化单元格不全

### ISSUE THREAD

**Issue by Eric0625** [qiankanglai/LoopScrollRect#40]
你好，使用中出现了一个问题，就是初始化的时候始终只初始化一半的界面，然后只要轻轻一碰单元格，剩余的就刷出来了，请问有可能是什么原因？

![default](https://user-images.githubusercontent.com/18132007/35815540-b538c7b4-0ad3-11e8-9677-4f9b5de18055.PNG)
![1](https://user-images.githubusercontent.com/18132007/35815541-b5780bd6-0ad3-11e8-82ea-6a6888ec6d17.PNG)

**Comment by qiankanglai** [comment]
能否提供一个可复现demo？

**Comment by Eric0625** [comment]
找到原因了，是anchor设置的问题
