### ISSUE TITLE
Unable to locate Instantiation source of prefabs

### ISSUE THREAD

**Issue by neosca** [qiankanglai/LoopScrollRect#41]
I have a custom prefab, which contains a Image element and a text element. I want to have each prefab instance a different name and image which will be updated using a lists with a custom method, however right now prefabs instantiate as soon I press the play button. 
Can you give some direction to achieve this?

**Comment by qiankanglai** [comment]
set totalCount=0 before play, and modify this value according to your use case along with Refill/Refresh
