### ISSUE TITLE
How to know when LoopScrollRect setup completed?

### ISSUE THREAD

**Issue by havudk1707** [qiankanglai/LoopScrollRect#43]
Dear,

Because I must do animation (use DOTween) with cells after all cell is filled to scroll view completed, 
I tried to do this when function RefillCells completed but it seems not working.

Could you let me know when scroll view is completed initial?

Thanks.

**Comment by havudk1707** [comment]
I found it. 
It will call LayoutComplete function
Thanks

**Comment by qiankanglai** [comment]
Hi, 
Sorry for the late reply. `LayoutComplete` works as UGUI builtin mechanism. Also you can add some event dispatcher in `UpdateItems` to check whether new items are added .
