### ISSUE TITLE
demo中VerticalScroll的列表，移除InitOnStart脚本还是能够渲染

### ISSUE THREAD

**Issue by howcooll** [qiankanglai/LoopScrollRect#44]
demo中VerticalScroll的列表，移除InitOnStart脚本，列表还是能够通过lateupdate方法中SetContentAnchoredPosition进行渲染，但是其他列表不会出现这样的情况。这在使用过程中可能会引起bug。

**Comment by qiankanglai** [comment]
这个地方是因为LoopScrollRect会试图“填满”整个区域，所以InitOnStart就算没有也会自己初始化
（这里加InitOnStart是为了一致性，确实不加也会渲染。。。）

如果要保证没有的时候不渲染，只能把ScrollRect的大小设为0

**Comment by qiankanglai** [comment]
修改CalculateOffset有一个潜在的问题是如果cell非常小的时候可能产生误判

我提交了一个修改 https://github.com/qiankanglai/LoopScrollRect/commit/271755686a47919619e5f08cb52b15774f69ef51
默认totalCount=0就不初始化，在InitOnStart里启动的时候设置进去（这样移除之后就不渲染了）
