### ISSUE TITLE
ScrollToCellCoroutine函数中else中计算offset有误

### ISSUE THREAD

**Issue by howcooll** [qiankanglai/LoopScrollRect#45]
if (directionSign == -1)
                            offset = reverseDirection ? (m_ViewBounds.min.y - m_ItemBounds.min.y) : (m_ViewBounds.max.y - m_ItemBounds.max.y);
                        else if (directionSign == 1)
                            offset = reverseDirection ? (m_ItemBounds.max.x - m_ViewBounds.max.x) : (m_ItemBounds.min.x - m_ViewBounds.min.x);
上面这段代码计算有误 会导致参数index = totalCount - 1时  needMoving不能置为false 。应该是min和max写反了，我修改后就没有问题了。
另外大佬能否添加一些content的滑动进度和添加一些content滑动结束的事件回调，现在有这样的需求都是自己添加。谢谢

**Comment by qiankanglai** [comment]
needMoving是你自己实现的参数麽？麻烦提供一个最小可复现demo

进度条可以直接用verticalNormalizedPosition/horizontalNormalizedPosition来读取进度，回调也可以加在这里的

**Comment by qiankanglai** [comment]
ok我知道什么问题了，你这样修改确实能停止滑动，但是位置就对不齐了。我来修改下
回调的话建议监听OnValueChanged

![image](https://user-images.githubusercontent.com/1546130/38913468-6c12eda4-430d-11e8-889b-3976e2b35c97.png)

**Comment by qiankanglai** [comment]
最新代码修复了这个问题 https://github.com/qiankanglai/LoopScrollRect/commit/7bc1d34ab24d3a5dd0892e1f7bd28b5e4ba96bf0

当Scroll的时候如果没法继续移动（譬如你举得例子 index=totalCount-1）会自动停下来

**Comment by howcooll** [comment]
thanks
