### ISSUE TITLE
小建议

### ISSUE THREAD

**Issue by zkyvette425** [qiankanglai/LoopScrollRect#46]
首先先谢谢你的功能。学习了一波。
不过有个地方，或许还可以有一点改进。
有时候需要增加的按钮，并不会做成单独的预制体，可能只是某个预制体的子按钮。
只想clone一下，你却写死了只能通过Resource的方式去加载。

**Comment by qiankanglai** [comment]
Resource加载这个我其实只是作为例子，因为不同项目都是有不同的资源管理机制的，如果你要修改的话其实我留了口子
https://github.com/qiankanglai/LoopScrollRect/blob/master/Assets/Scripts/LoopScrollPrefabSource.cs
