### ISSUE TITLE
Change element appear?

### ISSUE THREAD

**Issue by DEKAGATO** [qiankanglai/LoopScrollRect#47]
Man!
Sorry if i post in wrong place, I'm a newbie and have a question, hope that you can help :D. I'd like to make the list appear like zoom or scale it when drag and it become normal size when stop. What is the idea to make this. Thanks for your help?

**Comment by qiankanglai** [comment]
You could monitor it in `LateUpdate`: if `offset` is not zero, you can zoom or scale it
