### ISSUE TITLE
threshold

### ISSUE THREAD

**Issue by FatQuan** [qiankanglai/LoopScrollRect#48]
请问这个 threshold 变量是做啥的。有点儿没懂

**Comment by qiankanglai** [comment]
抱歉这个礼拜出去度假了，才回到有电脑的地方...

https://github.com/qiankanglai/LoopScrollRect/blob/master/Assets/Scripts/LoopVerticalScrollRect.cs#L61
这个地方的threshold是用来判断多大范围需要加或者删一个cell，一般threshold是按照最小cell size来算的。我举个例子：所有cell大小都是20，那么当空出5的时候不需要加新的cell，当空出25就需要

**Comment by keshaojiong** [comment]
感谢回复！刚看到邮件， 明白了
