### ISSUE TITLE
网格的时候，格子大小问题

### ISSUE THREAD

**Issue by wumiliu** [qiankanglai/LoopScrollRect#5]
当使用 GridLayoutGroup 时，一下代码有问题。或导致拉动的时候一直抖动
       protected override float GetSize(RectTransform item)
        {
             return LayoutUtility.GetPreferredHeight(item) + contentSpacing;
        }
因为用的是GridLayoutGroup ，所以格子的大小应该要从mLayout中获取
修改如下“：
        GridLayoutGroup mLayout;
        protected override float GetSize(RectTransform item)
        {
            // return LayoutUtility.GetPreferredHeight(item) + contentSpacing;
            return GetCellSize(item) + contentSpacing;
        }
        float GetCellSize(RectTransform item)
        {
            if (mLayout != null)
            {
                return mLayout.cellSize.y; //水平的这边用x
            }
            return LayoutUtility.GetPreferredHeight(item);
        }

**Comment by qiankanglai** [comment]
Fixed, thank you!
