### ISSUE TITLE
Refill后导致ScrollBar计算出错一直闪烁

### ISSUE THREAD

**Issue by keshaojiong** [qiankanglai/LoopScrollRect#50]
1、使用Github的DemoScene
2、其他的ScrollView都SetActive(false)只留下VerticalScroll做实验
3、运行场景，点击Clear，把初始化的50个干掉，把VerticalScrollBar设置为AutoHideAndExpandViewport，填TotalCount为12，点Refill复现

**Comment by qiankanglai** [comment]
![444](https://user-images.githubusercontent.com/1546130/42326015-81ab4254-809a-11e8-9fc0-2c51309f4d2b.gif)

**Comment by keshaojiong** [comment]
用的是​在Github下的工程 如果这种操作不允许请忽略 ^-^
另外有个问题 为什么threshold要算成itemSize*1.5 不是1倍，这里是考虑什么情况

2018-07-05 21:29 GMT+08:00 Kanglai Qian <notifications@github.com>:

**Comment by qiankanglai** [comment]
我用的是github工程，不过这种操作我确实之前没有考虑过
1.5是magic number =。=
