### ISSUE TITLE
请问RubberScale这个变量是有什么作用

### ISSUE THREAD

**Issue by keshaojiong** [qiankanglai/LoopScrollRect#51]

**Comment by qiankanglai** [comment]
那个是我们自己项目的需求，当拉出范围的时候粘滞手感的调节参数

**Comment by keshaojiong** [comment]
好的，我是试了下改变这个参数，发现没什么变化😥

2018-07-05 21:21 GMT+08:00 Kanglai Qian <notifications@github.com>:

**Comment by keshaojiong** [comment]
我错了，参数有效的，之前没用对😥

在 2018年7月6日 上午10:58，小柯 <keshaojiong@gmail.com>写道：
