### ISSUE TITLE
自动滑动

### ISSUE THREAD

**Issue by FatQuan** [qiankanglai/LoopScrollRect#53]
以垂直滑动为例子：当我的total 为-1的时候（-1 == 无限循环），我获取的verticalNormalizedPosition永远为0.5f，但是我需要拿到滑动中 verticalNormalizedPosition的值 来做自动滑动。请问这个自动滑动应该怎么实现

**Comment by qiankanglai** [comment]
无限循环暂时不支持这个功能-。-

**Comment by qiankanglai** [comment]
你可以在SrollToCell里修改下，我之前对无限循环做的限制比较多...
