### ISSUE TITLE
Cell Image Get Reloaded During Scrolling 

### ISSUE THREAD

**Issue by imran-nadeem** [qiankanglai/LoopScrollRect#55]
Hi,
If i have images in cells of the list then during scrolling the images get reloaded again and one cell image displays over the other till the new cell image is reloaded again.
Can we fix this ? 
Thanks.

**Comment by qiankanglai** [comment]
Sorry for the late reply,

You can modify https://github.com/qiankanglai/LoopScrollRect/blob/master/Assets/Scripts/LoopScrollPrefabSource.cs
 and cache prefabs with image so that won't be reloaded again.

**Comment by imran-nadeem** [comment]
Hi,
Please tell me what to modify and give me updated script code or anything.... all of my cells in list have images.
Thanks.

**Comment by qiankanglai** [comment]
Would you mind provide a complete example ?
