### ISSUE TITLE
Setting Content->GridLayoutGroup->Contraint to Flexible Causes Rendering Issue

### ISSUE THREAD

**Issue by richo0** [qiankanglai/LoopScrollRect#56]
In the Gridview Demo, in the VerticalScroll_Grid GameObject, setting the Content GridLayoutGroup's Contraint parameter to FlexIble causes a strange rendering bug. While scrolling, at certain points the row layout is contracted by one cell (and during scrolling it returns to the original cell count width).

**Comment by richo0** [comment]
P.S. This occurs under Unity 2018.1.6f1 - and to note, the content size fitter within the Content game object returns an error: "Parent has a type of layout group component, A child of a layout group should not have a Content Sizer fitter component, since it should be driven by the layout group."

**Comment by richo0** [comment]
I see now that Flexible layout is not supported. How can I fund you to support flexible layout?

**Comment by qiankanglai** [comment]
Sorry I tried before but cannot find a elegant way to calculate Flexible layout. 
Any suggestion may help and I'll try when I'm free
