### ISSUE TITLE
Need help: Item add

### ISSUE THREAD

**Issue by mtoanhcm** [qiankanglai/LoopScrollRect#58]
Hi @qiankanglai, thank you a lot, your script very helpful with me. It's work perfect. But I don't know how to add more item after scroll list created. I want to make chat system, all message will be save and add real time in chat box. Can I do that with your feature?

**Comment by qiankanglai** [comment]
Sorry for late reply (often I have time at weekends)

increase `totalCount` and call `RefreshCells(offset)`

**Comment by mtoanhcm** [comment]
Thanks @qiankanglai , it's work perfect!

**Comment by qiankanglai** [comment]
Just call `RefreshCells` again and it will fetch the data again (so you provide new data then)

**Comment by mtoanhcm** [comment]
Thanks @qiankanglai , I got it!
