### ISSUE TITLE
HELP ME...

### ISSUE THREAD

**Issue by sonxoans2** [qiankanglai/LoopScrollRect#6]
.
When i use your plugin. I got error:
Trying to remove myImage (UnityEngine.UI.Image) from rebuild list while we are already inside a rebuild loop. This is not supported.
UnityEngine.GameObject:SetActive(Boolean)
MyClass:ScrollCellIndex(Int32)
UnityEngine.UI.LoopScrollRect:LateUpdate()

how to fix this, please..

**Comment by qiankanglai** [comment]
would you mind post an example?

**Comment by sonxoans2** [comment]
This is myclass:
using System.Collections;
using UnityEngine.UI;
using UnityEngine;

public class TableBehavior : MonoBehaviour {
    //UI
    [SerializeField]
    Text lb_tenban;
    [SerializeField]
    Text lb_muccuoc, lb_can;
    [SerializeField]
    Slider slide_tinhtrang;
    [SerializeField]
    Slider slide_tinhtrang_XocDia;
    [SerializeField]
    Text numPlayer;
    [SerializeField]
    Image spriteLock;
    [SerializeField]
    Image backgroundSprite;
    [SerializeField]
    Color[] color;
    TableItem tableItem;

    void ScrollCellIndex(int index) {
        this.tableItem = GameControl.instance.listTable[index];
        if (index % 2 == 0) {
            backgroundSprite.color = color[0];
        } else {
            backgroundSprite.color = color[1];
        }
        lb_tenban.text = "Bàn " + tableItem.id;
        lb_muccuoc.text = BaseInfo.formatMoneyNormal(tableItem.money) + " " + Res.MONEY_FREE;
        lb_can.text = BaseInfo.formatMoneyNormal(tableItem.needMoney) + " " + Res.MONEY_FREE;
       
         bool isLock = tableItem.isLock == 1 ? true : false;
        spriteLock.gameObject.SetActive(isLock);

    }
}

**Comment by qiankanglai** [comment]
Hi, I've tried your script and works fine...Unity 5.3.6

```
public class ScrollIndexCallback1 : MonoBehaviour
{
    //UI
    [SerializeField]
    Text lb_tenban;
    [SerializeField]
    Text lb_muccuoc, lb_can;
    [SerializeField]
    Slider slide_tinhtrang;
    [SerializeField]
    Slider slide_tinhtrang_XocDia;
    [SerializeField]
    Text numPlayer;
    [SerializeField]
    Image spriteLock;
    [SerializeField]
    Image backgroundSprite;
    [SerializeField]
    Color[] color;
    //TableItem tableItem;

    void ScrollCellIndex(int index)
    {
        //this.tableItem = GameControl.instance.listTable[index];
        if (index % 2 == 0)
        {
            backgroundSprite.color = color[0];
        }
        else
        {
            backgroundSprite.color = color[1];
        }
        lb_tenban.text = "Bàn " + index;//tableItem.id;
        lb_muccuoc.text = ""+index * 2;//BaseInfo.formatMoneyNormal(tableItem.money) + " " + Res.MONEY_FREE;
        lb_can.text = "" + index * 3;// BaseInfo.formatMoneyNormal(tableItem.needMoney) + " " + Res.MONEY_FREE;

        bool isLock = index % 3 1= 0;//tableItem.isLock == 1 ? true : false;
        spriteLock.gameObject.SetActive(isLock);
    }
}
```

![qq 20160920120050](https://cloud.githubusercontent.com/assets/1546130/18657115/b4f62f76-7f29-11e6-98c3-084c1cbc964c.png)

Please upload an example so I can dig it

**Comment by sonxoans2** [comment]
Thank for reply..
I solved it successfully. when I remove scrollbar, no errors, I add it to the error occurred...
how to fix...

**Comment by qiankanglai** [comment]
the reason is: I haven't implemented scrollbar in fact 😢 
Other people have come up with it (https://github.com/qiankanglai/LoopScrollRect/issues/3). I made some effort before but this is far more complex than I think.

Do you need this seriously?

**Comment by sonxoans2** [comment]
Thank you for reply. I needed this. You can help me do it?

**Comment by qiankanglai** [comment]
I'll try implement this again with more constraints... would you provide more details about your requirements for me as reference?

**Comment by qiankanglai** [comment]
Sorry for very late reply...After a long struggle, I managed to implement scrollbar in https://github.com/qiankanglai/LoopScrollRect/commit/5104ca92170b6371288c2706f9984e011cf7e9b2

I've updated new README with demos.

**Comment by Nidre** [comment]
This issue seems to be appearing on Unity 5.6 again. Even for normal ScrollRect seems.
