### ISSUE TITLE
Loading each cell with images downloaded from server

### ISSUE THREAD

**Issue by guizmo01** [qiankanglai/LoopScrollRect#60]
Hi,

How can i load each cell with a png downloaded from server?

I already download images in persistant path then each image are added in a scriptable object in a list of images with data like file path, name, and url?

I know how to load texture from file into image component or raw image component i already have those method but how can i dynamically add them in order into you scrolls?

**Comment by guizmo01** [comment]
Another issue i am having is the actual positioning of those images i want to only show 1 image on the screen so it needs to take the whole screen, And I have the pool size set to 3 becuase loading images from persistant path can be slow and i have scrolls with 100 + images.

I have having issue with positioning it properly how i want. I think it is because of layout element and content size fitters. If i dont use those. the pooling does not work properly and instaantiate all images at once at soon as i start scrolling

**Comment by veboys** [comment]
I think this plugin is not suitable for your case.
