### ISSUE TITLE
Trying to remove ObjectPool --> GridView go wrong

### ISSUE THREAD

**Issue by tracer8** [qiankanglai/LoopScrollRect#61]
Hi, i try to remove object pool, use prefab instead of name and use only pure instantiate and Destroy of Unity. But it make grid view issue, can't scroll and recycle correct. Maybe your scroll rect use some config of GameObject to calculate scroll , and it must in pool?

I try another pool, with prefab yeah, but same result, your loop scroll rect only work with default object pool.

Bellow is my modify, please check , many thanks ! 
```
using UnityEngine;
using System.Collections;

namespace UnityEngine.UI
{
    [System.Serializable]
    public class LoopScrollPrefabSource 
    {
        public GameObject prefab;
        public int poolSize = 5;

        public virtual GameObject GetObject()
        {
            return Object.Instantiate(prefab);
        }

        public virtual void ReturnObject(Transform go)
        {
            go.SendMessage("ScrollCellReturn", SendMessageOptions.DontRequireReceiver);
            Object.Destroy(go.gameObject);
        }
    }
}
```

**Comment by tracer8** [comment]
@qiankanglai

**Comment by qiankanglai** [comment]
It may be the same with https://github.com/qiankanglai/LoopScrollRect/issues/25#issuecomment-352621703
Object.Destroy cannot remove item immediately, so some items may be destroyed multiply times so wired behavior happens

**Comment by tracer8** [comment]
@qiankanglai : I try to use DestroyImmediate, and it work like a charm. 
So i think reason of issue is LoopScrollRect call to ReturnObject multiple time per one item, how can i prevent that? Cause if i try to implement my own pool use prefab instead of your default pool, it's still have weird behavior.

**Comment by qiankanglai** [comment]
Imagine such case: now we have three cells out of bounds, so we need recycle them. Object.Destroy cannot take effect immediately so Destroy three times on the last item is not working as expected.

You just need to make sure ReturnObj takes effect immediately (no matter DestroyImmediate or Move out,or other methods)

**Comment by tracer8** [comment]
@qiankanglai : I try to modify your default Easy Object Pool, use prefab instead of string, and optimize its dictionary use int instead of string . And it's work like a charm now, thanks you!
Also, i removed your SendMessage, use Action , then if i need to modify my scroll item, i just register it and modify it through listener.

You can check it here, may be you can have some idea to upgrade this great LoopScrollRect.

**Thanks!**

**Comment by qiankanglai** [comment]
Sure, just modify code as you like.
In fact my working projects are using Prefab & Action too, but it is connected to other codes which is inconvenient for open source. So I choose a easy but not performance friendly way here, just as example
