### ISSUE TITLE
扩展需求，希望支持或帮助

### ISSUE THREAD

**Issue by veboys** [qiankanglai/LoopScrollRect#62]
您好，我现在遇到一个需求：
1)水平单行滚动列表，所有格子的大小相等
2)完成拖动操作后，需要将位置自动校正到刚好对其最靠近的一个格子上
3)当滚动完成后，需要知道当前显示区域的第一个格子的index

我暂时想到一个办法是过通过 horizontalNormalizedPosition、格子大小、间距、padding等去计算

请问您是否有更好的方法或建议，抑或是可以直接支持这种需求那就太感谢了！

**Comment by qiankanglai** [comment]
目前也只能这么干... 具体你可以参考下 https://github.com/qiankanglai/LoopScrollRect/blob/master/Assets/Scripts/LoopScrollRect.cs#L294 这段代码(滚动到某个cell)

你说的这个需求其实就是snap to index，在滚动结束之后判断最靠近边缘的是哪个鸽子，然后滑一下

最近我公司事情比较多，估计要过很久才有空弄。。。只能先给你一些现有代码参考

**Comment by leeve2008** [comment]
给大神一个建议：就是这个插件的clamp功能比较奇怪，一般情况下，这个clamp是无限循环最后一个栏目条不会被拖拽出边界，但是现在这个插件的功能是clamp只能在当前视窗加载栏目条（非加载的栏目条还在数据里面）拖拽。小弟找了很久没有找到怎么改（羞耻）

**Comment by qiankanglai** [comment]
你是说Movement Type改成Clamped么？那个模式下确实不好搞，因为我是根据两边超出范围大小来判断要不要加载下一个的，所以clamp模式下就始终不会触发了....这俩其实是天然互斥的，我得想想有没有办法绕开
