### ISSUE TITLE
对于异步加载的gameobject策略有什么好的建议吗。

### ISSUE THREAD

**Issue by EvilLee666** [qiankanglai/LoopScrollRect#63]
prefabSource.GetObject()  这个gameobject 目前项目这边都是异步才能拿到。 有什么好的结局方案吗。

**Comment by qiankanglai** [comment]
可以考虑做个placeholder，异步加载完之后替换

**Comment by EvilLee666** [comment]
那这个placeholder 需要和我要加载的gameobject尺寸上一致吧。

**Comment by EvilLee666** [comment]
thx
