### ISSUE TITLE
如何给整个列表设置背景？

### ISSUE THREAD

**Issue by Airsaid** [qiankanglai/LoopScrollRect#64]
请问一下，该如何给整个列表设置背景并且跟随 Item 滑动呢？

**Comment by zxt385189207** [comment]
请问有什么好的做法吗

**Comment by qiankanglai** [comment]
这个目前没有特别好的口子，最偷懒的做法是每个item背后挂一个 然后精准拼接... 比较干净的做法是在`m_Content.anchoredPosition`修改的地方配套设置
