### ISSUE TITLE
Is this possible to align all items at the center of the viewport?

### ISSUE THREAD

**Issue by ProgrammingLife** [qiankanglai/LoopScrollRect#65]
I tried to change horizontal scrollbar in Demo Set. I've set Total Count to 3 and then: Content layer -> Child Alignment -> Middle center. But it doesn't affect anything and it snaps all my three cells to the middle left. Not at the center horizontally. Is there a way to align at the center?

**Comment by qiankanglai** [comment]
LoopScrollRect cannot work with middle center now because I hard coded two directions (left-right, or up-down) I'll consider and implement it when I have time but maybe in 2019 😭
