### ISSUE TITLE
手机上运行使用初始化不全

### ISSUE THREAD

**Issue by EricCai1991** [qiankanglai/LoopScrollRect#67]
我在u3d上使用一下代码运行没问题
LVSRLoop.totalCount = m_members.Count;
LVSRLoop.RefreshCells();
但是我打包后在手机上运行发现没有刷新出来，需要拖动一下才会出来

**Comment by qiankanglai** [comment]
排查下Start时候的recttransform大小
我之前遇到过一个bug是界面刚弹出来的时候scale为0，过一帧之后才大小正常
