### ISSUE TITLE
SrollToCell偶尔出现回弹

### ISSUE THREAD

**Issue by EricCai1991** [qiankanglai/LoopScrollRect#68]
rt，不知道为什么会出现这个情况，不是必现，有时候例如跳到Index=24的位置，在跳到之后突然又跳回index = 23的位置，不知道为什么

**Comment by qiankanglai** [comment]
不好意思这个礼拜出差了，能不能提供一个demo复现

**Comment by EricCai1991** [comment]
随便生成100多项，然后调用SrollToCell(80)，滚动到指定位置后会往后弹，好奇怪

**Comment by EricCai1991** [comment]
可以了，我在调用SrollToCell方法里面先把
m_tempRate = m_DecelerationRate;
 m_DecelerationRate = 0;
然后在ScrollToCellCoroutine方法里面，
StopMovement();
 UpdatePrevData();
yield return null;
 decelerationRate = m_tempRate;
让跳转的时候decelerationRate 保持为0，然后在跳转完后的下一帧再还原回去就可以保证不会回弹了
