### ISSUE TITLE
多个预设体动态生成

### ISSUE THREAD

**Issue by Severn17** [qiankanglai/LoopScrollRect#69]
大佬，您的LoopScrollRect项目中有点问题想问下您，
我现在接受到的需求
根据数据在滑动列表中生成5种类型的选择框(五种预设体) 我应该如何怎么操作
我动态设置prefabSource.prefabName的话所有的框都会变成一种，望请解答

**Comment by qiankanglai** [comment]
https://github.com/qiankanglai/LoopScrollRect/blob/master/Assets/Scripts/LoopScrollPrefabSource.cs 修改这里，使用不同的PrefabSource

**Comment by Severn17** [comment]
已解决，多谢
