### ISSUE TITLE
Jumping rows.

### ISSUE THREAD

**Issue by t1az2z** [qiankanglai/LoopScrollRect#71]
Hi! I have an issue with Loop Vertical Scroll Rect: when I scroll it jumps up or down (depending on scroll direction) whenever a row get's close to a border of scroll rect. Is there a way to fix it? I use Grid Layout group set to one column.
Here is a gif, showing the problem.
![vodorobot_twitch](https://user-images.githubusercontent.com/14869912/58409172-2ebbc800-8078-11e9-8477-5a1d66940372.gif)

**Comment by qiankanglai** [comment]
Hi, I just come back from vacation. Would you mind provide a small exmaple?

**Comment by t1az2z** [comment]
What kind of example would you like? Repo with project or something else? Since this project is in development and under NDA i can only provide a small portion of it, but still can if needed.

**Comment by t1az2z** [comment]
https://github.com/t1az2z/LSR_bug her's the link to repo, showing the bug.

**Comment by qiankanglai** [comment]
Hi,

Pivot should be (0.5, 1) for **Content** under **Loop Vertical Scroll Rect**

**Comment by t1az2z** [comment]
Thank you alot!
