### ISSUE TITLE
性能优化建议

### ISSUE THREAD

**Issue by yyh9488** [qiankanglai/LoopScrollRect#72]
RectTransform nextItem = prefabSource.GetObject().GetComponent<RectTransform>;
修改成
RectTransform nextItem = prefabSource.GetObject().transform as RectTransform;
对性能有很大的帮助，实测iphone6没修改之前页面拖动卡顿修改之后流畅很多基本没有卡顿

**Comment by qiankanglai** [comment]
已合并，多谢
