### ISSUE TITLE
cell与cell之间的缝隙无法拖拽

### ISSUE THREAD

**Issue by UnityLearnerr** [qiankanglai/LoopScrollRect#73]
![image](https://user-images.githubusercontent.com/33482271/60327142-b8cfb700-99bd-11e9-8df9-025da29ebf46.png)
cell与cell之间的缝隙（如图红框所示），无法进行滑动操作，是我哪里用法出问题了吗？
我设置了VerticalLayoutGroup的Spacing

**Comment by UnityLearnerr** [comment]
我设置VerticalLayoutGroup的Spacing

**Comment by qiankanglai** [comment]
要有东西相应raycast target才能拖拽啊...

**Comment by xieheng** [comment]
把Rect Mask 2D换成Mask即可
