### ISSUE TITLE
Scrolling not working on android.. Working on Unity Editor

### ISSUE THREAD

**Issue by PrabhjotSingh-ANDDEV** [qiankanglai/LoopScrollRect#74]
something is wrong with android .. the scrolling not working...
EDIT : The Issue was . I was using it along with NGUI UI. so for some reason scrolling was working on editor but not on smartphones which was strange and i thought it was wrong.
I have to disable events from NGUI UI.. and then it started working on smartphones too. Scroll Rect is a pain. But this project is totally working fine.

**Comment by qiankanglai** [comment]
Would you mind provide a small example project?

**Comment by PrabhjotSingh-ANDDEV** [comment]
It was so strange,
I was using Ngui and with that I was using canvas.
It took me so much time to understand the problem but the issue was the
scroll rect was not getting the onDrag functions.
So i have to disable the events from ngui UI and then it started working.

**Comment by qiankanglai** [comment]
Maybe NGUI swallow touch event. I actually haven't tried UGUI along with NGUI yet.
