### ISSUE TITLE
grid的最后一行/列如果元素不满，则会出现问题

### ISSUE THREAD

**Issue by DumoeDss** [qiankanglai/LoopScrollRect#75]
以Demo场景的VerticalScroll_Grid为例，将默认填充60个元素改为33（大于显示一页的元素个数，且最后一行不满Constraint Count），ScrollBar的size与value计算皆会出错（不知道是不是feature）。

**Comment by DumoeDss** [comment]
对于Grid来说，如果最后一行没有填充满元素的话，计算的elementSize就会偏小，导致滚动条抖动。
因此对于没有填充满元素的情况下，计算elementSize时补充缺的个数，模拟最后一行也填充满即可。
添加两个变量，addCount用于补充itemTypeEnd - itemTypeStart，tmpTotalCount则用于代替totalCount。

> int tmpTotalCount;
        int addCount = 0;
        void AddCount()
        {
            addCount = 0;
            tmpTotalCount = totalCount;
            if (totalCount % contentConstraintCount != 0)
            {
                tmpTotalCount = totalCount + contentConstraintCount - (totalCount) % contentConstraintCount;
            }
            if ((itemTypeEnd - itemTypeStart) % contentConstraintCount != 0)
            {
                addCount = contentConstraintCount - (itemTypeEnd - itemTypeStart) % contentConstraintCount;
            }
        }

在UpdateScrollbars(Vector2 offset)修改m_HorizontalScrollbar.size之前调用AddCount()

>  //==========LoopScrollRect==========
                if (m_ContentBounds.size.y > 0 && totalCount > 0)
                {
                    //=====AddCount=====
                    AddCount();
                    //=====AddCount=====
                    m_VerticalScrollbar.size = Mathf.Clamp01(
                        (m_ViewBounds.size.y - Mathf.Abs(offset.y))
                        / m_ContentBounds.size.y
                        * (itemTypeEnd - itemTypeStart+addCount) / (float)tmpTotalCount
                        );
                }
                //==========LoopScrollRect==========

接着修改verticalNormalizedPosition，horizontalNormalizedPosition与SetNormalizedPosition()中计算elementSize的部分。

> //=====AddCount=====
                    float elementSize = m_ContentBounds.size.y / (itemTypeEnd - itemTypeStart+ addCount);
                    float totalSize = elementSize * (tmpTotalCount);
                    float offset = m_ContentBounds.max.y + elementSize * itemTypeStart;
                    //=====AddCount=====

**Comment by hemingfei** [comment]
这个问题很严重， 不仅仅是上面修复的问题，我参考上面的依旧抖动，是每刷新出新的一行就会整体错位抖动

**Comment by qiankanglai** [comment]
抱歉最近有点忙，周末我看下这个问题

**Comment by DumoeDss** [comment]
> 这个问题很严重， 不仅仅是上面修复的问题，我参考上面的依旧抖动，是每刷新出新的一行就会整体错位抖动

诶，是不是有地方没有修改全？所有Scrollbar相关的需要计算的地方都需要修改，如果有错位抖动就说明有地方没有改。

**Comment by DumoeDss** [comment]
> 这个问题很严重， 不仅仅是上面修复的问题，我参考上面的依旧抖动，是每刷新出新的一行就会整体错位抖动

诶，是不是有地方没有修改全？所有Scrollbar相关的需要计算的地方都需要修改，如果有错位抖动应该就是有地方没有改。
我fork了一份，修改了下，可以参考看看[https://github.com/DumoeDss/LoopScrollRect](https://github.com/DumoeDss/LoopScrollRect)

**Comment by qiankanglai** [comment]
我看了下这个问题是我之前写滚动条的时候忘记测试Grid未满情况了。master上我修复了一下，增加了TotalLines/StartLine/CurrentLines封装了一下，有点类似@DumoeDss 的做法。
@hemingfei 可以更新最新代码看下是否还有问题
