### ISSUE TITLE
GC太高

### ISSUE THREAD

**Issue by xieheng** [qiankanglai/LoopScrollRect#77]
使用layoutgroup貌似导致GC很高，有没有考虑优化呢？

**Comment by xieheng** [comment]
我profiler了一下，发现这些GC是LayoutGroup产生的，再深入看是由于GetComponent产生的，因为是在Editor下面（还没有真机测试过）我怀疑是由于Get不到组件产生的警告字符串引发的GC，不知道你在真机上查过这个问题没？

**Comment by qiankanglai** [comment]
LayoutGroup是我写这个的本质原因，就是因为不想自己做布局系统所以拿Unity原生的改的...
如果你的布局比较简单的话，可以干掉这块完全自己来，性能会好很多。不过我之前的项目需要复杂Layout所以就沿用了。

真机的话我们之前测试下来没有成为性能瓶颈，不过这个说实话是看元素量级的...

**Comment by xieheng** [comment]
好的，谢谢您的回复
