### ISSUE TITLE
When I used refill, pool was increasing!

### ISSUE THREAD

**Issue by StasiaKokoko** [qiankanglai/LoopScrollRect#79]
Good day! Thank you for your work~

I have a question: 
I have one scroll rect for several types of items. For example - you can select fruits, vegetables and berrys from one scroll rect. When categories selected, scroll rect was refilling. I noticed that with each select the pool was growing - 6, 12, 24 and so on. How can I fixed it?

**Comment by qiankanglai** [comment]
Could you provide a small example?

**Comment by StasiaKokoko** [comment]
[https://drive.google.com/open?id=1RPVligtcKJBKQgfsXszqtAovKALQyq8H](url) - look, I put the video and package!

**Comment by qiankanglai** [comment]
I just inspected your code and found this diff in your unitypackage:
```
 Assets/Scripts/LoopScrollPrefabSource.cs | 6 ++++++
 1 file changed, 6 insertions(+)

diff --git a/Assets/Scripts/LoopScrollPrefabSource.cs b/Assets/Scripts/LoopScrollPrefabSource.cs
index ec88bbe..63d1e21 100644
--- a/Assets/Scripts/LoopScrollPrefabSource.cs
+++ b/Assets/Scripts/LoopScrollPrefabSource.cs
@@ -17,6 +17,12 @@ namespace UnityEngine.UI
                 SG.ResourceManager.Instance.InitPool(prefabName, poolSize);
                 inited = true;
             }
+            var obj = SG.ResourceManager.Instance.GetObjectFromPool(prefabName);
+            if(obj==null)
+            {
+                SG.ResourceManager.Instance.InitPool(prefabName, poolSize);
+                obj = SG.ResourceManager.Instance.GetObjectFromPool(prefabName);
+            }
             return SG.ResourceManager.Instance.GetObjectFromPool(prefabName);
         }
```

You added one more GetObjectFromPool and this is the reason leak happens.
