### ISSUE TITLE
Scroll doesn't work correctly if movement type is set to clamped

### ISSUE THREAD

**Issue by roointan** [qiankanglai/LoopScrollRect#80]
Won't scroll correctly if movement type is set to clamped

**Comment by qiankanglai** [comment]
Could you provide a small example?

**Comment by roointan** [comment]
Yes! In the demo, from hierarchy, select VerticalScroll, and in the inspector change movement type from Elastic to Clamped.
The scroll by drag will no longer work.
I changed it back to Elastic and that was enough for me, but I though I should let you know about it.
And thanks for the great product! it helped a lot!

**Comment by qiankanglai** [comment]
Sorry for late reply.
I've fixed in master branch and you could have a try. Any other bug report is welcomed!

Thanks

**Comment by roointan** [comment]
Thanks a lot for fixing this!
