### ISSUE TITLE
Much more Items are generated when scrolling the scrollbar quickly 

### ISSUE THREAD

**Issue by 18fanna** [qiankanglai/LoopScrollRect#81]
In the Function "UpdateItems", the strategy of Update is DELETE first, then ADD ,which may generate much more Items . My unity version is Unity 2019.2.11f 
Does this problem occure in your project?

**Comment by qiankanglai** [comment]
Is ObjectPool generating much more items than it actually needs?
I havn't encountered such problem yet. Would you mind provide a small example ?
