### ISSUE TITLE
能不能添加一个刷新之后自动滚到底部的方法

### ISSUE THREAD

**Issue by zhouyang8304** [qiankanglai/LoopScrollRect#9]

**Comment by zhouyang8304** [comment]
这样可以用来做聊天图文混排

**Comment by qiankanglai** [comment]
我之前是用Refill+修改content的anchoredPosition来实现的，有项目用到了这个功能...主要是出于接口设计不漂亮，我就没放到这里

**Comment by FelixDYS** [comment]
Hi,您好，前辈，又是我，之前的那个问题我用记录transfrom下的child名字做对比，基本实现了。最近遇到了个新问题，想咨询下您。用您的这个插件，在滑动的过程，生成新的子物体Item后，发消息到子物体的脚本中，我修改了这个子物体上的一个UnityEngine.Text.text的内容。例如Text.text = "Hello World",在这个时候会卡顿那么一下，滑动很不流畅，本来应该是滑动过后就出来的，但是新创建的Item会卡顿一下才能出来。我查找了下 有网友说是因为动态字体，UI动态赋值会这样，请问您有什么建议？

**Comment by qiankanglai** [comment]
不好意思这个周末出差了回的比较慢，你最好先对比试验下如果是修改Sprite会不会卡顿
然后才能确定是Text的问题还是LoopScrollRect问题

如果是动态字体的话，有一个简单粗暴的方法是`Font.RequestCharactersInTexture` 你可以去看下这个API

**Comment by FelixDYS** [comment]
非常感谢您的回复，您能回复我，真的十分感谢。我一句句的代码测试确定了，确实是Text的问题，我会试试这个方法，非常感谢前辈您😙

在 2017年3月27日 上午10:35，Kanglai Qian <notifications@github.com>写道：
