### ISSUE TITLE
第一次快速滑动会产生很多item

### ISSUE THREAD

**Issue by EvilLee666** [qiankanglai/LoopScrollRect#90]
在比较极端的情况下，列表元素很多 然后我从头拖到尾 按照目前的代码会在while中实例化很多item 因为池里面没有，且入池的操作也是在while以后进行的。
是否可以改为看不见部分先入池再去取。理论上应该可行。具体代码改动水平太差没法实现。楼主是否有空提供帮助。

**Comment by qiankanglai** [comment]
最近的提交已经修改了（前段时间实在太忙，才有空响应- -
- 先delete再new item
- 我做了一个更加激进的优化：直接delete时候不返回pool，而是直接标记下，这样setparent消耗都干掉了

你可以试试master分支最新版本，有问题随时联系

**Comment by qiankanglai** [comment]
补交了一个优化：如果滑动特别快（1帧里超过1页）原来会有挺多无效的对象池操作，我改成直接计算了。不过对于不规则大小的cell可能会有误差

**Comment by EvilLee666** [comment]
多谢大大。

**Comment by greyhu** [comment]
最新的一次特别快的滑动优化有bug，会产生多余的item。

**Comment by greyhu** [comment]
弹性，往上滑出弹回的时候

**Comment by qiankanglai** [comment]
收到~我最近事情比较多，有空了排查下~

**Comment by qiankanglai** [comment]
@greyhu 
优化的commit 我单拆到opt分支(master先回滚了)。不过我本地测试不出边界情况... 是否方便录一个视频或者别的可复现方式，我来修一下
