### ISSUE TITLE
Need help for instant scrolling to index or row 

### ISSUE THREAD

**Issue by crmagicxxx** [qiankanglai/LoopScrollRect#91]
Hi

Can you please give me any advice about how can I implement some method inside LoopScrollRect class that can go directly to position of a cell index or row? For example, scroll.SetVerticalPositionByIndex(int cellIndex) or scroll.SetVerticalPositionByRow(int row)? So in attached example I would like to set position to index 50 or row 10...

I know you have ScrollToCell which goes by subroutine, but that approach doesn't work for me as I need instant position

Thanks

![screen](https://user-images.githubusercontent.com/1320690/100618656-6ade8180-331c-11eb-8779-5a5e4edb38b3.png)

**Comment by crmagicxxx** [comment]
Ok, I found a solution, to Refill cells from the first cell in row index
But it would be nice to have instant position setting methods nevertheless

**Comment by qiankanglai** [comment]
Hi,
`RefillCells` is just what does the work. But I agree with your option so I refactor `ScrollToCell` a bit to jump when `speed<=0`.
commit has been made: https://github.com/qiankanglai/LoopScrollRect/commit/fdc28b4352a0fd16156e06b4201526667a0c2495
