### ISSUE TITLE
滚动列表初始显示为逆向时，滑动的惯性明显收到影响，滚动条也不自然会后上下抽搐的现象

### ISSUE THREAD

**Issue by helpking** [qiankanglai/LoopScrollRect#94]
属性设定如图
![QQ图片20210125162639](https://user-images.githubusercontent.com/3415624/105680289-76b87f80-5f2a-11eb-88d9-39c593c1e6d5.png)

只有选中这个属性，初始化显示在最末端，往回回滚的时候
滚动列表的惯性滑动明显有被什么卡住似的。
这个时候滚动条在往上滚动的同时，也有明显的上下抖动似的抽搐现象。

其他的整体来说，还是很优秀的。
完美解决了循环再生列表，还支持单元格动态高度自适应。 完美！

**Comment by qiankanglai** [comment]
收到，我这周末来跟进下。
方便整个inspector截图一下嘛? 我看下anchored position设置，或者直接网盘来一份sample scene?

**Comment by helpking** [comment]
我这边有一些业务的内容，暂时分离不出来。不过你的这个工程的项目中，选上逆向的标志位点上，也会出现这个现象的。
我这个issue中有上传截图！能显示吗？

发自我的iPhone

在 2021/01/25，23:28，Kanglai Qian <notifications@github.com> 写道：

﻿

收到，我这周末来跟进下。
方便整个inspector截图一下嘛? 我看下anchored position设置，或者直接网盘来一份sample scene?

**Comment by qiankanglai** [comment]
哈喽，能看到截图。
按照这个描述的话，我猜测是锚点设置问题。如果需要设置ReverseDirection时，同时需要设置对应Content的锚点~以下是两种情况的对比。如果没有对应设对的话确实会有问题，这块因为Content是Scroll的子节点所以可能会被忽视。
![image](https://user-images.githubusercontent.com/1546130/106375777-2af25400-63ca-11eb-9502-e4ba11421bfa.png)
![image](https://user-images.githubusercontent.com/1546130/106375779-334a8f00-63ca-11eb-9202-a399c7944546.png)

麻烦确认下是不是这个情况，如果是的话我回头加一些编辑器下的报错提示从而便于定位。
