### ISSUE TITLE
跳转的时候，如果让要调整的目标在正中间

### ISSUE THREAD

**Issue by EricCai1991** [qiankanglai/LoopScrollRect#95]
调用SrollToCell方法跳转的时候，要跳转的目标都是在最上面，现在需要跳转的目标是在是屏幕中间，请问下怎么做才好

**Comment by qiankanglai** [comment]
抱歉春节回来才看到...
屏幕中间这个只能自己算下offset了，基本思路就是根据content size和每个cell的大小算一下距离最上面有多少的偏差
