### ISSUE TITLE
RefillCells在多行多列时还是有些Bug

### ISSUE THREAD

**Issue by dingxuejia** [qiankanglai/LoopScrollRect#96]
if (totalCount >= 0 && itemTypeStart % contentConstraintCount != 0)
  {
      itemTypeStart = (itemTypeStart / contentConstraintCount) * itemTypeStart;
  }

这个代码是不是有点问题   后面是不是应该乘contentConstraintCount

而且你demo中  中间那个横排的loop  用RefillCells 传大于16的值就会出现 总数变少或者变多的bug

**Comment by dingxuejia** [comment]
我知道你的bug出在哪里了
            StopMovement();
            itemTypeStart = reverseDirection ? totalCount - offset : offset;
            itemTypeEnd = itemTypeStart;

            if (totalCount >= 0 && itemTypeStart % contentConstraintCount != 0)
            {
                itemTypeStart = (itemTypeStart / contentConstraintCount) * itemTypeStart;
            }

这里有两个bug   一个是   itemTypeStart = (itemTypeStart / contentConstraintCount) * itemTypeStart  这里后面乘的值不对

另一个是itemTypeEnd = itemTypeStart; 这句代码应该放在 更后面

**Comment by qiankanglai** [comment]
谢谢，这块代码确实写得有问题
