### ISSUE TITLE
调用SetNormalizedPosition时会多次调用NewItem的问题

### ISSUE THREAD

**Issue by shadylyf321** [qiankanglai/LoopScrollRect#97]
比如 列表有200个item，当前normalValue =0。当设置normalValue = 1时，在UpdateItems会先将items补满至200个，再将多余的删除掉。请问有没有合适的解决方案呢？

**Comment by qiankanglai** [comment]
这个问题之前确实存在，后来我在 https://github.com/qiankanglai/LoopScrollRect/commit/7ff22dddb2c80208018c276c0d502403a50f68c0 换了个思路修复了下~我刚用最新的代码尝试直接normalValue设置0和1跳变的时候不会触发全部补满了。如果能触发创建200个item那应该还有问题，麻烦看下怎么稳定复现，我来修一下。

顺便如果是normalValue=1这种特殊情况，其实可以直接调用RefillFromEnd也可以

**Comment by shadylyf321** [comment]
明白了 感谢回复👍 YUNFEI LIU ***@***.*** 签名由 网易邮箱大师 定制 在2021年05月04日 14:56，Kanglai Qian 写道： 这个问题之前确实存在，后来我在 7ff22dd 换了个思路修复了下~我刚用最新的代码尝试直接normalValue设置0和1跳变的时候不会触发全部补满了。如果能触发创建200个item那应该还有问题，麻烦看下怎么稳定复现，我来修一下。 顺便如果是normalValue=1这种特殊情况，其实可以直接调用RefillFromEnd也可以 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
