### ISSUE TITLE
如何实现一个不滚动 直接跳转的扩展?

### ISSUE THREAD

**Issue by jonny91** [qiankanglai/LoopScrollRect#98]
用什么思路更好修改一些。看到很多东西都放在了LateUpdate里

**Comment by qiankanglai** [comment]
直接跳转的话推荐使用RefillCells或者RefillCellsFromEnd(可选参数是偏移量)，或者直接设置normalizedValue也可以。目前最新的代码已经优化过，避免了跨页跳转时大量无用的生成逻辑。

**Comment by JingFengJi** [comment]
我修改了ScrollToCell接口使其滑动居中，居中结束后得到了horizontalNormalizedPosition，然后直接设置horizontalNormalizedPosition时 ScrollRect并未居中之前的Cell，有一定的偏差呢

**Comment by qiankanglai** [comment]
我测试了下先滑动到30的位置，保存verticalNormalizedPosition；然后移动走之后设置verticalNormalizedPosition看上去没问题...
“居中”具体是指？

![new](https://user-images.githubusercontent.com/1546130/117560416-0d91ed80-b07d-11eb-9a78-6a7b1d989c16.gif)

**Comment by JingFengJi** [comment]
“居中”是指 此Cell 位于View Rect中间位置，目前RefillCells 接口拓展了下  支持定位居中，没有使用上面说的修改horizontalNormalizedPosition坐标方式。“居中”一个CenterIndex，根据Cell的宽度计算出一个StartIndex和EndIndex，然后填充数据后修改Content的anchoredPosition，以此实现的居中定位Cell

**Comment by qiankanglai** [comment]
要不fork个仓库提交下修改，我拉下你的代码看下

**Comment by JingFengJi** [comment]
可以的，上周跟 @zxsean 约了下，提交个版本

**Comment by qiankanglai** [comment]
哈哈哈好，麻烦了~

**Comment by jonny91** [comment]
您好，你的邮件我已收到。会尽快查阅。
